### ISSUE TITLE
Ion stuck on "Reusing keep-alive socket" whenever re-executing (refreshing) same request again.

### ISSUE THREAD

**Issue by vipulpurohit** [koush/ion#104]
I'm fetching JSON with GSON in Ion lib but whenever i'm re-executing the same request, the request never goes in 'onCompleted' event. If i'm executing request first time then everything works perfect but in second time it stuck on 'Reusing keep-alive socket' here is the log  :

 12-04 12:15:33.640: D/MyLogs(1902): (0 ms) http://192.168.1.31/CompanyList.svc/GetCompanyList: preparing request
12-04 12:15:33.640: D/MyLogs(1902): (0 ms) http://192.168.1.31/CompanyList.svc/GetCompanyList: Executing request.
12-04 12:15:33.640: D/MyLogs(1902): (0 ms) http://192.168.1.31CompanyList.svc/GetCompanyList: Reusing keep-alive socket

If I lock the screen on this state and then unlock, it complete the request.

**Comment by Abhi0725** [comment]
@koush you said this issue should be fixed in 1.2.5. I am using 2+ and getting this issue since last one month. Posted on stackoverflow, opened a issue here, even tweeted you about this. Can you please confirm if this issue has been fixed or not?

**Comment by kaizenx** [comment]
This bug is happening again in 2.1.8

**Comment by askarali** [comment]
This bug is happening again in 2.1.9
