### ISSUE TITLE
"closing out socket (exception)", then the code never returns with a callback

### ISSUE THREAD

**Issue by j3g** [koush/ion#152]
I am connecting to a web service over https. On my internal test server my connection is successful. On my external amazon instance Ion hangs (I believe the server is closing the connect...still investigating). I have successfully talked to the web service using Firefox with the same parameters.

If I turn on VERBOSE I see the information "closing out socket (exception)".
After that I never receive a callback about the error but instead wait indefinitely.
If I cancel the Future I see "java.util.concurrent.CancellationException"

This is one point I traced it to:
if (data.exception != null || !data.socket.isOpen()) {
and data.exception == null, therefore  !data.socket.isOpen()  is the error

I am still tracing back to figure out why no callback is happening...

**Comment by koush** [comment]
pretty sure this was a bug in spdymiddleware that was fixed very recently.

https://github.com/koush/AndroidAsync/commit/8aabbd1fb850e4a8cea54c45c8de9dc715c5c70a

**Comment by you1b231** [comment]
Still exist the problem "closing out socket (exception)" on aws resources.

**Comment by jessejohnson** [comment]
@you1b231 I'm also experiencing this problem. Since last week, I've only been able to consistently get data from my server twice. Every other time, the application waits indefinitely.

I set the log level to `VERBOSE` and that's how I found this exception.

I'm using Android 6.0 with Ion 2.0.0. My server is also on AWS.

Have you found a solution to this? I'm considering changing my networking library.

**Comment by dabeli1** [comment]
The year is 2017
The issue still exists

I wanted to throw TimeoutException when ..
`closing out socket (exception)`

happens, the error occurs usually in less than 700 ms but user have to wait for 30 seconds and that sucks. Can be solved by renewing keep alive ? socket ? invisible rope connecting ion and the server ? i fixed it with a ping request following the actual request.

```
// ENCAPSULATED PING CALL
Ion.with(context).load(url)
	....
	.setTimeout(700)
	...
	.setCallback(new FutureCallback<String>() {
	@Override
	public void onCompleted(Exception e, String result) {
			
		// ACTUAL CALL
		Ion.with(context).load(url)
			....
			.setTimeout(30 * 1000)
			....
			.setCallback(new FutureCallback<String>() {
			@Override
			public void onCompleted(Exception e, String result) {
				// Stuff Happens
			});
			
	});

```

Thanks
- Dabeli Masal Wadi
