### ISSUE TITLE
Support for using resources for image loading

### ISSUE THREAD

**Issue by raylee4204** [koush/ion#153]
Is there any way to load image sources from resources, assets or files?

**Comment by BordoBereli** [comment]
I could`t find if I can use the Ion for downloaded gif file to display it from localy saved directory on ImageView. 
Ion.with(imageView).load("/data/data/cihazkesif/app_ImageDir/img_94_236.gif"); also
Uri url = Uri.fromFile(filePath);
                    Ion.with(imageView).load(url.getPath());
So I couldn`t figure it out if there is a way...
