### ISSUE TITLE
Distortion on transform

### ISSUE THREAD

**Issue by douglaskayama** [koush/ion#161]
I'm trying to use Ion with [RoundedImageView](https://github.com/vinc3m1/RoundedImageView) following the [sample](https://github.com/vinc3m1/RoundedImageView/blob/master/example/src/com/makeramen/example/PicassoFragment.java) provided there for Picasso.

I'm doing 
`Ion.with(context, url).withBitmap().placeholder(R.drawable.placeholder).transform(transformation).intoImageView(imageView);`

and the transformation is:

```
Transform transformation = new Transform() {
    @Override
        public Bitmap transform(Bitmap bitmap) {
            Bitmap scaled = Bitmap.createScaledBitmap(squaredBitmap, cornerRadius, cornerRadius, false);
            Bitmap transformed = RoundedDrawable.fromBitmap(scaled).setScaleType(ImageView.ScaleType.CENTER_CROP).setCornerRadius(cornerRadius).setOval(isOval).toBitmap();
            if (!bitmap.equals(scaled)) bitmap.recycle();
            if (!scaled.equals(transformed)) bitmap.recycle();

            return transformed;
        }

    @Override
        public String key() {
            return "rounded_radius_" + cornerRadius + "_oval_" + isOval;
        }
}
```

`cornerRadius` is the same width as the ImageView (it's a regular ImageView, from android, not from the library) to make it round. `isOval` I tried both true and false. When I use Picasso, everything runs fine, but when I use Ion, the image shows up stretched (keeping the original proportion, although the transformation squares it), so, I suspect it's either the Transform or when the image is put into ImageView.

I also tried to square it to exact size:

```
Bitmap squaredBitmap;
if (bitmap.getWidth() >= bitmap.getHeight()) {

    squaredBitmap = Bitmap.createBitmap(
            bitmap,
            bitmap.getWidth() / 2 - bitmap.getHeight() / 2,
            0,
            bitmap.getHeight(),
            bitmap.getHeight()
            );

} else {

    squaredBitmap = Bitmap.createBitmap(
            bitmap,
            0,
            bitmap.getHeight() / 2 - bitmap.getWidth() / 2,
            bitmap.getWidth(),
            bitmap.getWidth()
            );
}

Bitmap scaled = Bitmap.createScaledBitmap(squaredBitmap, cornerRadius, cornerRadius, false);
Bitmap transformed = RoundedDrawable.fromBitmap(scaled).setScaleType(ImageView.ScaleType.CENTER_CROP).setCornerRadius(cornerRadius).setOval(isOval).toBitmap();

if (!bitmap.equals(squaredBitmap)) {
    bitmap.recycle();
}

if (!squaredBitmap.equals(scaled)) {
    squaredBitmap.recycle();
}

if (!scaled.equals(transformed)) {
    scaled.recycle();
}
return transformed;
```

with no success. Using Picasso leads to no problem though, so I suspect an issue on Ion side.

I'd like to help debug and solve the issue, if it's indeed an issue.

**Comment by vaiiibhav** [comment]
what is  RoundedDrawable?
