### ISSUE TITLE
how to get the status code of the response?

### ISSUE THREAD

**Issue by letroll** [koush/ion#17]

**Comment by estebanmk** [comment]
Hi!
I'm trying to read http code response, but when an http error 500 occurs (internal server error) response is null.
So?

**Comment by rayworks** [comment]
@estebanmk 
You need to check together with the backend guy(s) or review the doc of the API  you just called.

> Response status codes beginning with the digit "5" indicate cases in which the server is aware that it has encountered an error or is otherwise incapable of performing the request.

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_error
