### ISSUE TITLE
Timeout on upload POST

### ISSUE THREAD

**Issue by UXDart** [koush/ion#18]
Hi
I'm setting the timeout to
Ion.with(context, url)....
ion.setTimeout(60 \* 60 \* 1000);

but I get timouts exception anyway. is the timeout only for receiving data? because I get it when uploading a lot of data, when doing a POST. is there anyway to set the timeout on that case?

TIA!

**Comment by BapaiahMandava** [comment]
hi,

what does **setTimeout(-1)** do?
And even the public void **onCompleted(Exception ex, WebSocket webSocket)** method is being calling the webscoket every minute?

Pls throw some light why is this behaviour.
