### ISSUE TITLE
Timeout Exception after Idling

### ISSUE THREAD

**Issue by mirzakukic** [koush/ion#197]
I am not sure if I am doing something wrong but I have an issue with the Ion library when I leave my application to idle for a few minutes. When I return to it and trigger some action that calls the Ion library it very often fails with a timeout exception for the first time (but all subsequent runs succeed).

I use Ion in the following way:

``` java
Ion.with(this, "myurl").noCache().asString().setCallback(new FutureCallback<String>() {
    @Override
    public void onCompleted(Exception arg0, String arg1) {
        if (arg0 == null && arg1 !=null)
            ;
    }
});
```

Also I have noticed that I get connection java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer) error in the log sometimes. But I do not think it is related to the timeout exception.

**Comment by sasingh0818** [comment]
Hello Kaush

Can you please share any update whether the issue issue of MultiPart upload  reported by dinobud reolved?
