### ISSUE TITLE
setBodyParameters - how to use

### ISSUE THREAD

**Issue by er1z** [koush/ion#200]
Prety n00b question:

```
Map<String, List<String>> params = null;

        params.put("email", Arrays.asList("mail@mail.pl"));
        params.put("password", Arrays.asList("pass"));
```

But if I use above within `setBodyParameters`, my App just crashes.

How to correctly specify an argument for this function? Nothing is covered by samples.

Cheers!

**Comment by sumanpula** [comment]
how to specify setBodyParams(String,Long),

could you define a method with setParams(K,V);
