### ISSUE TITLE
ION is not making HTTP request calls 

### ISSUE THREAD

**Issue by xriztot** [koush/ion#204]
Hi Koush, 

ION is not making HTTP request calls in my HTC desire 4.0.3 and in GenyMotion Emulator using 4.4.2 OS.

It's working fine in Samsung s4 mini and in native android emulator.

Can you please help me in this matter what's the problem? Am i missing something.

I'm using simple ion GET, POST calls.

Thanks in Advance.

**Comment by ils-anshub** [comment]
When I am doing login with facebook through ionic its giving an error like -" The application may be doing too much work on its main thread" many times ...  and I am not getting why this happen? Actually the same code is running in API 18 but giving this lines in logcat in API 19.

Any help?
