### ISSUE TITLE
FATAL EXCEPTION: ion-ion. java.lang.out of memory error

### ISSUE THREAD

**Issue by libinsatheesan** [koush/ion#227]
/////////////////////////////////// 1. /////////////////////////////////

05-15 12:30:07.830: E/AndroidRuntime(22024): FATAL EXCEPTION: ion-ion
05-15 12:30:07.830: E/AndroidRuntime(22024): java.lang.OutOfMemoryError
05-15 12:30:07.830: E/AndroidRuntime(22024):    at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:48)
05-15 12:30:07.830: E/AndroidRuntime(22024):    at java.nio.ReadWriteHeapByteBuffer.<init>(ReadWriteHeapByteBuffer.java:49)
05-15 12:30:07.830: E/AndroidRuntime(22024):    at java.nio.ByteBuffer.allocate(ByteBuffer.java:52)
05-15 12:30:07.830: E/AndroidRuntime(22024):    at com.koushikdutta.async.ByteBufferList.obtain(ByteBufferList.java:473)
05-15 12:30:07.830: E/AndroidRuntime(22024):    at com.koushikdutta.async.http.ResponseCacheMiddleware$CachedSocket.spewInternal(ResponseCacheMiddleware.java:730)
05-15 12:30:07.830: E/AndroidRuntime(22024):    at com.koushikdutta.async.http.ResponseCacheMiddleware$1.run(ResponseCacheMiddleware.java:166)
05-15 12:30:07.830: E/AndroidRuntime(22024):    at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:675)
05-15 12:30:07.830: E/AndroidRuntime(22024):    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:692)
05-15 12:30:07.830: E/AndroidRuntime(22024):    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:600)
05-15 12:30:07.830: E/AndroidRuntime(22024):    at com.koushikdutta.async.AsyncServer.access$4(AsyncServer.java:589)
05-15 12:30:07.830: E/AndroidRuntime(22024):    at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:549)

////////////////////////////////////////// 2. //////////////////////////////////////////

Aslo logging shows another out of memory error

05-15 12:51:24.770: E/dalvikvm-heap(22565): Out of memory on a 1787616-byte allocation.
05-15 12:51:24.770: I/dalvikvm(22565): "pool-3-thread-1" prio=5 tid=17 RUNNABLE
05-15 12:51:24.770: I/dalvikvm(22565):   | group="main" sCount=0 dsCount=0 obj=0x417bd920 self=0x582f0a40
05-15 12:51:24.770: I/dalvikvm(22565):   | sysTid=22600 nice=0 sched=0/0 cgrp=apps handle=1479478928
05-15 12:51:24.770: I/dalvikvm(22565):   | schedstat=( 7458111000 875239000 3876 ) utm=720 stm=25 core=1
05-15 12:51:24.770: I/dalvikvm(22565):   at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
05-15 12:51:24.770: I/dalvikvm(22565):   at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:426)
05-15 12:51:24.770: I/dalvikvm(22565):   at com.koushikdutta.ion.bitmap.IonBitmapCache.loadBitmap(IonBitmapCache.java:150)
05-15 12:51:24.770: I/dalvikvm(22565):   at com.koushikdutta.ion.LoadBitmap$1.run(LoadBitmap.java:81)
05-15 12:51:24.770: I/dalvikvm(22565):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
05-15 12:51:24.770: I/dalvikvm(22565):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
05-15 12:51:24.770: I/dalvikvm(22565):   at java.lang.Thread.run(Thread.java:856)
05-15 12:51:24.770: D/skia(22565): --- decoder->decode returned false
05-15 12:51:25.400: I/dalvikvm-heap(22565): Clamp target GC heap from 48.717MB to 48.000MB
05-15 12:51:25.400: D/dalvikvm(22565): GC_FOR_ALLOC freed 59K, 3% free 47785K/49159K, paused 72ms, total 72ms
05-15 12:51:25.400: I/dalvikvm-heap(22565): Forcing collection of SoftReferences for 1800736-byte allocation
05-15 12:51:25.460: I/dalvikvm-heap(22565): Clamp target GC heap from 48.717MB to 48.000MB
05-15 12:51:25.460: D/dalvikvm(22565): GC_BEFORE_OOM freed <1K, 3% free 47785K/49159K, paused 65ms, total 65ms

**Comment by Nemisis** [comment]
I too am receiving this error: 

    java.lang.OutOfMemoryError
       at java.nio.ByteBuffer.allocate(ByteBuffer.java:56)
       at com.koushikdutta.async.ByteBufferList.obtain(ByteBufferList.java:504)
       at com.koushikdutta.async.http.filter.InflaterInputFilter.onDataAvailable(InflaterInputFilter.java:43)
       at com.koushikdutta.async.http.filter.GZIPInputFilter.onDataAvailable(GZIPInputFilter.java:140)
       at com.koushikdutta.async.Util.emitAllData(Util.java:22)
       at com.koushikdutta.async.http.filter.ChunkedInputFilter.onDataAvailable(ChunkedInputFilter.java:87)
       at com.koushikdutta.async.Util.emitAllData(Util.java:22)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.onDataAvailable(AsyncSSLSocketWrapper.java:230)
       at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:217)
       at com.koushikdutta.async.Util.emitAllData(Util.java:22)
       at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
       at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
       at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

I am using the following request: 

```java
Ion.with(context).load(url).setTimeout(TIMEOUT).group(group)
    .addHeader(Headers.AUTHORIZATION, authToken)
    .asString().withResponse().get();
```

Not sure why this would be happening? I am simply attempting to load a JSON REST API (no images).

**Comment by sud007** [comment]
As @koush  mentioned it may happen while loading images from the local resource.
He suggested loading images from the local stream instead.

So for local images i rather used the plain ImageView and created inputStream for and generated the drawable from the stream. you can look for the answer here on SOF.


http://stackoverflow.com/a/29874618/1149398

**Comment by Xerosigma** [comment]
I've hit the same issue. It was working fine in a ListView but porting over to a RecyclerView furnished this error. Not sure it's entirely related to Ion :/
