### ISSUE TITLE
Ignoring SSL verification

### ISSUE THREAD

**Issue by HishamGhosheh** [koush/ion#232]
Hi, thanks for the great project, I wonder if there's an option to disable SSL verification.
I'm not asking for self signed certificated support, I just need to completely ignore ssl verification. I do understand the risks but I need to disable it any way.

Currently receiving this exception:
com.koushikdutta.async.http.ConnectionClosedException: connection closed before response completed.

For the HttpClient I was able to succeed using this answer
http://stackoverflow.com/a/4837230
But I still prefer using Ion.

Best regards.

**Comment by turbogunhawk** [comment]
I have the same issue, limited to 5.0, using 2.1.3. Downgrading to 2.0.7 works fine.

**Comment by Pitel** [comment]
For future me, this is the code that makes it work:

```java
Ion.getDefault(this).getHttpClient().getSSLSocketMiddleware().setTrustManagers(new TrustManager[] {new X509TrustManager() {
	@Override
	public void checkClientTrusted(final X509Certificate[] chain, final String authType) throws CertificateException {}

	@Override
	public void checkServerTrusted(final X509Certificate[] chain, final String authType) throws CertificateException {}

	@Override
	public X509Certificate[] getAcceptedIssuers() {
		return new X509Certificate[0];
	}
}});
```
