### ISSUE TITLE
SocketException: recvfrom failed: ETIMEOUT

### ISSUE THREAD

**Issue by Rameshv** [koush/ion#273]
i am getting tis timeout exception when trying to download some zip files. 

```
E java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
E at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:545)
E at libcore.io.IoBridge.recvfrom(IoBridge.java:521)
E at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:314)
E at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:276)
E at com.koushikdutta.async.SocketChannelWrapper.read(SocketChannelWrapper.java:24)
E at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:157)
E at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:755)
E at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:600)
E at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
E at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:549)
E Caused by: libcore.io.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
```

File size varies from 5MB to 20 MB. It abruptly stops the download in the middle and throws this error. 

But the same time, the image downloads are working fine. 

This occurs on master. 

This works fine if i use the android default http library.

similar issue is logged here https://github.com/koush/AndroidAsync/issues/188

**Comment by taotaomydream** [comment]
can you help me? I meeting  about this question 
this is my error log：
`[2022-09-15 12:20:27:3,ERROR] fcc.com.mpos.common.PosHttpClient$PosHttpException: recvfrom failed: ETIMEDOUT (Connection timed out)
	at fcc.com.mpos.common.PosHttpClient.postJson(PosHttpClient.java:148)
	at fcc.com.mpos.common.BasicService$BasicDataRequest.post(BasicService.java:91)
	at fcc.com.mpos.data.service.PayService$PayDataRequest.allinOrderQuery(PayService.java:1593)
	at fcc.com.mpos.data.service.PayService.allinPayOrderQuery(PayService.java:1155)
	at fcc.com.mpos.data.core.payment.PaymentAllin$1$1.run(PaymentAllin.java:137)
	at fcc.com.mpos.common.PosTask.run(PosTask.java:43)
Caused by: java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)`
