### ISSUE TITLE
Add support for self signed certificates

### ISSUE THREAD

**Issue by koush** [koush/ion#3]
Need support for custom SSL Context and TrustManagers for use during SSL handshaking.

**Comment by anti43** [comment]
facing the same issue i guess - after setting up the custom trust manager, ion.with calls still fail for the self signed cert

**Comment by koush** [comment]
ion uses the same http client every call.

**Comment by anti43** [comment]
@koush yes, but as the examples setup

    AsyncHttpClient.getDefaultInstance()

and *Ion.getDefault(c)* is on

    new AsyncHttpClient(new AsyncServer("ion-" + name));

the example code does not match the usage of *Ion.with* ..
That was what was confusing here I guess.

**Comment by koush** [comment]
ion.with calls into ion.getDefault.

**Comment by koush** [comment]
oh, you were assuming that ion uses the default asynchttpclient. nah, it has it's own.

**Comment by roland-batovski** [comment]
@koush So I'm using <a href=http://www.codeproject.com/Articles/826045/Android-security-Implementation-of-Self-signed-SSL#_comments>this</a> code (the very last option) to create a new HttpClient that uses my own certificate stored in a .bks file in res/raw. As you can see, all the key loading is done there. I am also using Ion with my application and I'm having difficulty figuring out where I can initialize Ion to use the correct SSLContext and TrustManagers. Cheers!

**Comment by HughJeffner** [comment]
Is there a reason `.setTrustManagers(...)` must be called as well?  I thought the `SSLContext` is initialized with a set of trust managers, this seems like a duplication of effort.

**Comment by ibnux** [comment]
i use Cloudflare Free SSL and getting Error
this is how i resolve it https://gist.github.com/ibnux/4bf68e16e1228b6568a349c583d1cd32

**Comment by muhammad-naderi** [comment]
for future reference : https://gist.github.com/muhammad-naderi/fad2c163ac61e0b7282209c07f5dadf5
