### ISSUE TITLE
Timeout error in ION (the same works fine from browser) on simple GET or POST 

### ISSUE THREAD

**Issue by VladVuk** [koush/ion#328]
Hi Koush,

I am trying to use the ION library and it prefer to return error Timeout mostly.

Can you help and exlain how to use it to avoid timeout error for unknown reason.
When I try the same GET or POST , JSON or XML http request from web browser it works fine but with ION I don't know why mostly or when it returns Timeout error.

To simplify explanation you can see my screen (with error debug messages and the code above). 
The code is your simplified Twitter sample code but I use http requests on local notebook over wifi.

![image](https://cloud.githubusercontent.com/assets/8056983/3924617/354aeea8-23df-11e4-99df-d319dcde95a0.png)

Thanks
Vlad

**Comment by subodh-malgonde** [comment]
I am on Ion 2.1.0 and I am still having this issue. Some of my GET calls randomly fail with a TimoutException. I have enabled verbose logging on my calls, here is one such log:

    D/Ion Logs - cities fetch﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: preparing request
    D/Ion Logs - cities fetch﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: preparing request
    I/Ion Logs - cities fetch﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: Using loader:com.koushikdutta.ion.loader.HttpLoader@41c86150
    D/Ion Logs - cities fetch﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: Executing request.
    I/Ion Logs - cities fetch﹕ (9 ms) http://api.peppertap.com/location/v1/cities/: Response may be served from conditional cache
    D/Ion Logs - cities fetch﹕ (9 ms) http://api.peppertap.com/location/v1/cities/: Reusing keep-alive socket
    E/Ion Logs - cities fetch﹕ (30022 ms) http://api.peppertap.com/location/v1/cities/: Connection error
    E/Ion Logs - cities fetch﹕ null
    java.util.concurrent.TimeoutException
            at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
            at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**This issue happens only on some calls and usually happens when 2-3 calls happen sequentially.**

**Comment by koush** [comment]
@subodh-malgonde please open a new issue with this log and a code sample

**Comment by koush** [comment]
@subodh-malgonde The latest version is 2.1.3 btw.

**Comment by subodh-malgonde** [comment]
Updated ion to 2.1.3, the problem still seems to be there. I have created a new issue with sample code and log [#528](https://github.com/koush/ion/issues/528)
