### ISSUE TITLE
how can I use ion's http cache when device is offline?

### ISSUE THREAD

**Issue by ares89** [koush/ion#345]

**Comment by FreakTheMighty** [comment]
Hey @koush, I'm using the example `CacheOverrideMiddleware` to override the `Cache-Control` header, but when I'm offline I get this error:

`java.net.UnknownHostException: Unable to resolve host "example.com": No address associated with hostname`

Do you have any thoughts on what is causing this?

**Comment by FreakTheMighty** [comment]
The caching works on the emulator, so I have some more investigating to do.
