### ISSUE TITLE
ion sets the imageView height to a wrong value

### ISSUE THREAD

**Issue by stoefln** [koush/ion#378]
I dont know why this is happening (see white area below and above image)

![bildschirmfoto 2014-10-03 um 15 42 25](https://cloud.githubusercontent.com/assets/562800/4511522/a403a09c-4b35-11e4-9faf-00570b42104b.png)

My ImageView is displayed in a listview item. My adapter code looks like this:

<pre>
if (node.getImageUrl() != null) {
    ivImage.setVisibility(View.VISIBLE);
    Ion.with(ivImage)
            .placeholder(R.drawable.anne_eli_icons_set_up_anne_eli_logo_530px)
            //.error(R.drawable.error_image)
            //.animateLoad(android.R.anim.cycle_interpolator)
            .animateIn(android.R.anim.fade_in)
            .load("http://app.anne-eli.at/" + node.getImageUrl().getUrlBig());

} else {
    ivImage.setVisibility(View.GONE);
}
</pre>

My imageview layout like this:

<code>
<pre>
&lt;LinearLayout ...
    &lt;ImageView
            android:id="@+id/fragment_appointment_list_item_article_iv_image"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:src="@drawable/anne_eli_icons_set_up_anne_eli_logo_530px"
            android:background="@color/gray1" />
&lt;/LinearLayout>
</pre>
</code>

Can you help me?

**Comment by koush** [comment]
Try 2.0. This has been reworked.

**Comment by muraliremod7** [comment]
How can i display different images from URL into Listview using common class.Can you help me
