### ISSUE TITLE
centerCrop on ImageView appears to be ignored for error resource resulting in distorted image

### ISSUE THREAD

**Issue by dredenba** [koush/ion#384]
When using the resize and centerCrop to resize the image loaded from the url it all seems to work okay. The image appears to be resize and appropriately scaled in the ImageView. However in the case where the image fails to load and the error image resource is loaded instead. The issue I have noticed is that the error resource image is not being resized and scaled appropriately. In my specific usage the "generic_image" error image is actually getting "squished" vertically resulting in a distorted image. The resource image is a different aspect ratio than the ImageView (close to square image in an image view that is landscape ) so distortion is quite noticeable.

"myImageView" starts with the scale type being set to CENTER_CROP

this results in a distorted error image:
```
Ion.with( myImageView )
       .error( R.drawable.generic_image )
       .resize( myImageWidth, myImageHeight )
       .centerCrop()
       .load( "http://badurl/that/fails" );
```
while this properly scales the error image:
```
Ion.with( myImageView )
       .error( R.drawable.generic_image )
       .load( "http://badurl/that/fails" );
```

is there a way to correct this?

**Comment by koush** [comment]
use a 9 patch for the error.
