### ISSUE TITLE
Doesn't support CircleImageView

### ISSUE THREAD

**Issue by AllenDang** [koush/ion#389]
Seems Ion 1.3.8 cannot work with CircleImageView (https://github.com/hdodenhof/CircleImageView).

When I do below code, I got "width and height must be > 0".

CircleImageView imgAvatar = ...;
Ion.with(imgAvatar).load("http://...");

I tried Picasso with same statement and it works fine. Hope this issue could be fixed, I really like to use one async-loading lib in my project and I hope it could be Ion. :)

**Comment by koush** [comment]
I'll think I'll be able to add support for this one:
https://github.com/vinc3m1/RoundedImageView

This seems to be the most widely used one, is based off Romain Guys sample, and supports handling/inspecting LayerDrawables. If I refactor IonDrawable to inherit from LayerDrawable, I may be able to get it to work without any changes in the RoundedImageView library.

**Comment by schwiz** [comment]
Oh nice that sounds like a good solution! Is the plan to able to pass an
array of Drawables you'll use for the IonDrawable constructor?

On Sun, Feb 22, 2015 at 3:19 PM, Koushik Dutta <notifications@github.com>
wrote:

> I'll think I'll be able to add support for this one:
> https://github.com/vinc3m1/RoundedImageView
>
> This seems to be the most widely used one, is based off Romain Guys
> sample, and supports handling/inspecting LayerDrawables. If I refactor
> IonDrawable to inherit from LayerDrawable, I may be able to get it to work
> without any changes in the RoundedImageView library.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koush/ion/issues/389#issuecomment-75460537>.
>



-- 
*Nathan Schwermann*
*785-312-0080*
*http://schwiz.net <http://schwiz.net>*

**Comment by koush** [comment]
No, the underlying drawables will just be accessible to anyone.

IonDrawable is used to catch the draw events and trigger fetches. It also manages fading between placeholder/error/bitmap.

Basically, since it will be a layer drawable, you can do something like:

getDrawable/setDrawableByLayerId to replace a layer with your own. That's exactly what RoundedImageView does to change how a drawable is drawn.

https://github.com/vinc3m1/RoundedImageView/blob/master/roundedimageview/src/main/java/com/makeramen/roundedimageview/RoundedDrawable.java#L92

**Comment by schwiz** [comment]
Oh good I was looking at the LayerDrawable documentation and didn't see
that setLayerById method. Looks perfect!

On Sun, Feb 22, 2015 at 3:29 PM, Koushik Dutta <notifications@github.com>
wrote:

> No, the underlying drawables will just be accessible to anyone.
>
> IonDrawable is used to catch the draw events and trigger fetches. It also
> manages fading between placeholder/error/bitmap.
>
> Basically, since it will be a layer drawable, you can do something like:
>
> getDrawable/setDrawableByLayerId to replace a layer with your own. That's
> exactly what RoundedImageView does to change how a drawable is drawn.
>
>
> https://github.com/vinc3m1/RoundedImageView/blob/master/roundedimageview/src/main/java/com/makeramen/roundedimageview/RoundedDrawable.java#L92
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koush/ion/issues/389#issuecomment-75461211>.
>



-- 
*Nathan Schwermann*
*785-312-0080*
*http://schwiz.net <http://schwiz.net>*

**Comment by koush** [comment]
Now supports RoundedImageView on the layers branch
https://github.com/vinc3m1/RoundedImageView

Testing it in AllCast now.

From my searching, RoundedImageView was the only library that supports LayerDrawables properly (iterates through the layers looking for BitmapDrawables to round).

Doesn't work with GIFs.

**Comment by schwiz** [comment]
Cool I got RoundedImageView to work pretty easily. 

It would be good to add an IonImageView and some kind of common interface to replace these types of calls in RoundedImageView 'public static Drawable fromDrawable(Drawable drawable)' so we can easily add our own custom drawables without using RoundedImageView.

**Comment by koush** [comment]
https://github.com/koush/ion/blob/master/ion-sample/src/com/koushikdutta/ion/sample/RoundedImageViewSample.java
