### ISSUE TITLE
GIF corruption

### ISSUE THREAD

**Issue by koush** [koush/ion#405]
http://cdn.funnyisms.com/5ab61f7b-581f-49ff-9a4f-1290f879baf2.gif *

https://www.youtube.com/watch?v=1g92bcNhE_I&feature=youtu.be

**Comment by Saren-Arterius** [comment]
My users are complaining about this too. Is there a chance to reference android-gif-drawable library or use a existing solution?

**Comment by darshan1689** [comment]
I also have the same problem please help.thank you
