### ISSUE TITLE
Global error handling

### ISSUE THREAD

**Issue by HughJeffner** [koush/ion#414]
Is there a way to register a callback to receive all exceptions?  (Preferably with the associated Future)

I tried inserting a SimpleMiddleware and overriding onHeadersReceived and can get the http response code but that is about as far as I got.

**Comment by ianwhite2** [comment]
Can you provide some example  or pointer to handle Exception

**Comment by HughJeffner** [comment]
Error handling middleware:
```
public class MySimpleMiddleware extends SimpleMiddleware {

    @Override
    public void onResponseComplete(OnResponseCompleteDataOnRequestSentData data) {
        
        if (data.exception != null) Log.e("MySimpleMiddleware", "Handle error here", data.exception);
        super.onResponseComplete(data);
        
    }

}
```
Insert it into pipeline:

`Ion.getDefault(ctx).getHttpClient().insertMiddleware(new MySimpleMiddleware());`
