### ISSUE TITLE
Gif images leave trace from each frame

### ISSUE THREAD

**Issue by raylee4204** [koush/ion#416]
I'm trying to use GIF images that have transparent background. 

However, each frame leaves a trace behind - take a loot at the screenshot below.

![device-2014-11-21-133417](https://cloud.githubusercontent.com/assets/2085389/5147383/3b72cf3e-7183-11e4-9816-5ea95e9a19a5.png)

**Comment by Fleker** [comment]
This might be an issue in Lollipop.

I did have gifs work properly a while back for a Glass project. I tried to revert back to that Gradle version, but the issue occurred every time. 

In 2.+, the gif will appear to spawn infinitely without any issue.
In 1.2.0 and up, the gif does again appear to spawn continuously. However, the area is refreshed when the animation ends. It also seems slow, as if there's a memory issue.
In 1.1.5 and below, there doesn't seem to be any animation, nor any method to make it animate. It's just the first frame wrapped in a black box.

**Comment by raylee4204** [comment]
@Fleker this happens on a kitkat device as well. It's related to the new way to handle gif images in 2.+ I believe.

**Comment by koush** [comment]
Yeah, reprod the issue. It's a regression in 2.0. Will fix.

**Comment by koush** [comment]
this gif is using dispose code 3 (previous), which means leave the previous gif in frame. I think the gif is actually corrupt.

If i manually change the dispose code to 2 (clear), it looks correct.

**Comment by Fleker** [comment]
I'm intending to use this project on an app to load gifs from a url. I notice the same effect with all of them. Example (http://www.pkparaiso.com/imagenes/xy/sprites/animados/zubat.gif)

I'm not sure what dispose code is being used, but I would like to remove all traces each frame.

**Comment by koush** [comment]
Nevermind, I see what is going on now. The dispose code handling is incorrect in the GifDecoder.

**Comment by raylee4204** [comment]
This issue has been reappeared in the latest version.

**Comment by Fleker** [comment]
I'm not seeing this behavior as of yesterday.

**Comment by raylee4204** [comment]
This issue has reappeared in the latest version

**Comment by Fleker** [comment]
As of two days ago the issue was fixed for me.

**Comment by raylee4204** [comment]
It used to work on 2.0.7 but this issue appeared in 2.0.9.

**Comment by koush** [comment]
Just fixed this
