### ISSUE TITLE
animateLoad and animateIn?

### ISSUE THREAD

**Issue by mmrk09** [koush/ion#418]
Ion.with(imageView)
  .placeholder(R.drawable.placeholder_image)
  .error(R.drawable.error_image)
  .animateLoad(spinAnimation)
  .animateIn(fadeInAnimation)
  .load("http://example.com/image.png");

I get that you need image resources for place holder and error but what about the animations?  Are they GIF resources or something else created in the android project?

**Comment by leeyikjiun** [comment]
What exactly is this spinAnimation? How do I add a indeterminate progress bar while loading the image?

I have tried:
```
Ion.with(imageView)
     .animateLoad(android.R.anim.progress_indeterminate_rotation_material)
     .load(source)
```
but met with a cannot resolve symbol 'progress_indeterminate_rotation_material'

and also tried copying that directly into my resource folder but met with a `Unknown animation name: objectAnimator`

**Comment by Solum** [comment]
I wonder if there's a working example of this.

**Comment by mhamann** [comment]
Anyone ever find an example?

**Comment by carlosesteven** [comment]
/res/anim/loading.xml
`<?xml version="1.0" encoding="UTF-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <rotate
            android:fromDegrees="0"
            android:toDegrees="360"
            android:pivotX="50%"
            android:pivotY="50%"
            android:duration="1000"
            android:repeatMode="reverse"
            android:repeatCount="infinite"
            android:startOffset="0"
    />
</set>`

CODE IMPLEMENTATION
Ion.with( view.pagina )
            .placeholder( R.drawable.ic_img_placeholder )
            .error( R.drawable.ic_img_error )
            .animateLoad( R.anim.loading)
            .load( url_picture_to_load )`
