### ISSUE TITLE
libgmscore.so Error - All Requests Get Interrupted

### ISSUE THREAD

**Issue by eygraber** [koush/ion#437]
The past few days, my requests have been randomly getting interrupted. Tonight (naturally in middle of a client demo), all requests started failing. I grabbed the following from the logs following the first request going out and the first failure coming in. I'm using ion 2.0.1

``````
12-09 23:54:43.426    5523-5806/com.me I/dalvikvm﹕ DexOpt: mismatch dep name: '/data/dalvik-cache/system@framework@qcmediaplayer.jar@classes.dex' vs. '/system/framework/WfdCommon.odex'

12-09 23:54:43.426    5523-5806/com.me E/dalvikvm﹕ /system/framework/com.android.media.remotedisplay.jar odex has stale dependencies

12-09 23:54:43.427    5523-5806/com.me I/dalvikvm﹕ DexOpt: mismatch dep name: '/data/dalvik-cache/system@framework@qcmediaplayer.jar@classes.dex' vs. '/system/framework/WfdCommon.odex'

12-09 23:54:43.427    5523-5806/com.me E/dalvikvm﹕ /system/framework/com.android.location.provider.jar odex has stale dependencies

12-09 23:54:43.433    5523-5806/com.me D/dalvikvm﹕ Trying to load lib /data/app-lib/com.me-2/libgmscore.so 0x435e7ca0

12-09 23:54:43.433    5523-5806/com.meE/dalvikvm﹕ dlopen("/data/app-lib/com.me-2/libgmscore.so") failed: dlopen failed: library "/data/app-lib/com.me-2/libgmscore.so" not found

12-09 23:54:43.433    5523-5806/com.me E/ProviderInstaller﹕ Unable to load native code from /data/app-lib/com.me-2/libgmscore.so

12-09 23:54:43.434    5523-5806/com.me D/dalvikvm﹕ Trying to load lib /data/app-lib/com.google.android.gms-2/libgmscore.so 0x435e7ca0

12-09 23:54:43.438    5523-5806/com.me D/dalvikvm﹕ Added shared lib /data/app-lib/com.google.android.gms-2/libgmscore.so 0x435e7ca0

12-09 23:54:43.438    5523-5806/com.me D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.google.android.gms-2/libgmscore.so 0x435e7ca0, skipping init

12-09 23:54:43.440    5523-5806/com.me E/ProviderInstaller﹕ libgmscore version mismatch (0 vs. 6587)```
``````

**Comment by ruchitshah2109** [comment]
hey koush have you updated in gradle dependency???

**Comment by younes0** [comment]
this has been fixed

**Comment by dongseok0** [comment]
Same issue here.
Using gradle with 2.+

**Comment by kivo360** [comment]
I have the issue too. I have no idea where to start in debugging this.

**Comment by koush** [comment]
Is this crashing or just showing in the logs?

**Comment by dstreet323** [comment]
Its a lib issue downgrade back to the old play service update it in the phone. View the update thru your settings>application manager> there will be a certain version number. You can go apkmirror.com and download the apk. Once you download the apk. Drop it in the download folder on your device. Go to file manager>select the apk in the download folder and install it to your device and you should be good to go.

**Comment by koush** [comment]
@dstreet323 is this a crash bug or just a log issue?

**Comment by dstreet323** [comment]
This is a lib folder issue. This specific(libgmscore.so) .so file is located in the Google Play Service Apk(GmsCore.apk). You will have to open it with 7zip and pull the libs and place them in the lib folder.

**Comment by dongseok0** [comment]
@koush I'm having log but lib is working. Can I ignore the log?

**Comment by koush** [comment]
Yes, you can ignore it. That's how how conscrypt searches for the lib path.

**Comment by koush** [comment]
@kruton ping

**Comment by kruton** [comment]
Not much that I can do about it. It's from the VM on the phone (https://android.googlesource.com/platform/dalvik/+/gingerbread/vm/Native.c#342)

**Comment by koush** [comment]
thanks for the heads up @kruton !

**Comment by tux-world** [comment]
i have this problem too in this time. i'm using new version of gradle and latest version of Ion
```
 libgmscore version mismatch (0 vs. 9256)
```

**Comment by the90sartist** [comment]
@koush I'm having trouble while connecting with the https api. It is saying "Conscrypt initialization failed" and NoClassDefFoundError :+1:  Lcom/google/android/gms/security/ProviderInstaller; Didn't find class "com.google.android.gms.security.ProviderInstaller".

Any solution for this?

**Comment by koush** [comment]
@the90sartist that error is benign. that just means you aren't using google play services. I need more of a call stack.
