### ISSUE TITLE
Feedly SSL never gives a result when doing 2 queries through Conscrypt.

### ISSUE THREAD

**Issue by robUx4** [koush/ion#443]
As the thread #428 seems to be closed and unattended I raise a new issue. In short when doing 2 parallel connections to Feedly through Conscrypt, only one of them returns, when you're lucky. In some case none of the calls ever return anything. That's an issue in Ion 1.4.1 and Ion 2.0.2. The problem may and probably exists with other servers. That means **Ion on Android 5.0 is unusable to do HTTPS queries**.

I did a sample project to demonstrate the issue with Ion 2.0 https://github.com/robUx4/testSSLv3/tree/dual_ssl_ion2.0 And one for Ion 1.4.1 https://github.com/robUx4/testSSLv3/tree/dual_ssl_141

I have this issue with the Play Services 6.5.87 on Nexus 5 with Android 5.0 and GenyMotion 4.1.1 with conscrypt set. It seems to be a timing issue and changing the delay between the 2 calls can trigger the bug or not. By enabling logs in Ion, it seems the sockets are correctly connected but the failing one(s) **never transmit any data and never time out**.

For now I have to use HttpUrlConnection for all my SSL calls until this is resolved in Ion.

**Comment by Xerosigma** [comment]
I'm still seeing this issue in 2.1.3 - Can someone confirm what which release includes this fix?

Thank you.

**Comment by Xerosigma** [comment]
I no longer seem to be seeing this in **2.2.1** can someone confirm?
