### ISSUE TITLE
I get "libgmscore.so failed: No such file or directory" with no SSL!!

### ISSUE THREAD

**Issue by IRMobydick** [koush/ion#445]
When I run app on Asus Kooe ( Fonepad 7 - android 4.4.2), app crashed and get this:

`12-23 15:32:16.944: W/SoundPool(5978): App requested 0 channels`
`12-23 15:32:17.224: E/IMGSRV(5978): :0: PVRDRMOpen: TP3, ret = 51`
`12-23 15:32:17.224: E/IMGSRV(5978): :0: PVRDRMOpen: TP3, ret = 53`
`12-23 15:32:17.224: E/IMGSRV(5978): :0: PVRDRMOpen: TP3, ret = 54`
`12-23 15:32:17.224: E/IMGSRV(5978): :0: PVRDRMOpen: TP3, ret = 54`
`12-23 15:32:17.224: E/IMGSRV(5978): :0: PVRDRMOpen: TP3, ret = 54`
`12-23 15:32:17.244: E/IMGSRV(5978): :0: PVRDRMOpen: TP3, ret = 57`
`12-23 15:32:17.244: D/dalvikvm(5978): Trying to load lib /data/app-lib/com.may3am.parsvid-1/libgmscore.so 0x439e2760`
`12-23 15:32:17.254: E/(5978): open file /data/app-lib/com.may3am.parsvid-1/libgmscore.so failed: No such file or directory`
`12-23 15:32:17.254: E/dalvikvm(5978): dlopen("/data/app-lib/com.may3am.parsvid-1/libgmscore.so") failed: dlopen failed: library "/data/app-lib/com.may3am.parsvid-1/libgmscore.so" not found`
`12-23 15:32:17.254: E/ProviderInstaller(5978): Unable to load native code from /data/app-lib/com.may3am.parsvid-1/libgmscore.so`
`12-23 15:32:17.254: D/dalvikvm(5978): Trying to load lib /data/app-lib/com.google.android.gms-1/libgmscore.so 0x439e2760`
`12-23 15:32:17.264: D/houdini(5978): [6002] Loading library(version: 4.0.8.45720 RELEASE)... successfully.`
`12-23 15:32:17.274: D/OpenGLRenderer(5978): Enabling debug mode 0`
`12-23 15:32:17.294: D/houdini(5978): [6002] Unsupported feature (ID:0x20e00149).`
`12-23 15:32:17.294: A/libc(5978): Fatal signal 11 (SIGSEGV) at 0xdead0000 (code=1), thread 6002 (ion-ion)`

![log](https://cloud.githubusercontent.com/assets/4468890/5537645/8394f90e-8aba-11e4-8186-8b0ee21453cc.png)

**Comment by IRMobydick** [comment]
@koush
I got still this error in 2.0.5 version? :(
How can handle this issue?! Help me :|

**Comment by koush** [comment]
Try disabling conscrypt, but I don't think this is ion. This error log is benign, it happens any time you install the conscrypt provider.

I think this is your actual error:

12-23 15:32:17.294: A/libc(5978): Fatal signal 11 (SIGSEGV) at 0xdead0000 (code=1), thread 6002 (ion-ion)

Some native code call is crashing your app. Probably bad firmware on that asus.
