### ISSUE TITLE
Unable to use ion as UrlImageViewHelper alternative

### ISSUE THREAD

**Issue by vitali84** [koush/ion#447]
Hey,
Great library! really enjoy it at Funtomic Kizi andorid app.

We are currently using:
UrlImageViewHelper.loadUrlDrawable(context, game.thumb, 1728000000);
In order to preload images, and cache them for our game catalog in the background and use those images afterwards in online/offline mode.
We a haven't found a way to do this using Ion, as it looks as it saves the images in memory only and not in device storage.

By the way the issue we are having with UrlImageViewHelper is that it sometimes reaches max thread pool causing "java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@413e3bd0 rejected from java.util.concurrent.ThreadPoolExecutor@410df9e8[Running, pool size = 128, active threads = 128, queued tasks = 10, completed tasks = 24]"
exception

Thanks for help!

**Comment by koush** [comment]
ion will respect any cache headers in the http response. if you want to force caching, implement a middleware that overrides cache control headers. you can start with this:

https://github.com/koush/AndroidAsync/blob/master/AndroidAsyncSample/src/com/koushikdutta/async/sample/middleware/CacheOverrideMiddleware.java
