### ISSUE TITLE
Feature: force cache

### ISSUE THREAD

**Issue by oinegue** [koush/ion#448]
In my app, I'm downloading some csv files from a remote server that I know they are not changing in few minutes.
That server that does not allow cache
```
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
```
I don't own server, neither I can ask to change headers.
Is it possible to force caching nevertheless?

**Comment by koush** [comment]
Extend and implement SimpleMiddleware to do this. Insert it into the http client.

**Comment by koush** [comment]
somnething like this

https://github.com/koush/AndroidAsync/blob/master/AndroidAsyncSample/src/com/koushikdutta/async/sample/middleware/CacheOverrideMiddleware.java
