### ISSUE TITLE
Clear bitmap cache doesn't work

### ISSUE THREAD

**Issue by AykutCevik** [koush/ion#449]
I'm executing the method ```Ion.getDefault(getApplicationContext()).getBitmapCache().clear();``` on a menu item click, but can still see cached files in Android Device Monitor.

Doing this in an emulator on Nexus 5 with Lollipop. 

Any ideas to solve this problem?

Also thanks for this awesome library!

**Comment by koush** [comment]
that just clears the bitmap cache, which is in memory. clear the resposne cache to clear the file storage for all http responses as well.

**Comment by ToxicBakery** [comment]
To clarify, are you suggesting we use the following to clear the disk cache combined with clearing the bitmap cache?

```
Ion.getDefault(context).getCache().clear()
```

**Comment by koush** [comment]
Yes
