### ISSUE TITLE
Multipart Doesn't Support Adding Stream As MultipartFile

### ISSUE THREAD

**Issue by keremkusmezer** [koush/ion#456]
Hi ,

The current requirement for my project is that i can add a file from byte array as multipart file to the multipart file upload, as far as i can see, i cannot do it.

**Comment by SukharevAndrey** [comment]
It also means that ION doesn't support chunked transfering, at least I have not found any way to do it :(

**Comment by koush** [comment]
ion does chunked transfering. You can do a byte array as a multipart file by specifying your own implementation of part. Or write teh byte array to a file file, and then send it.

**Comment by SukharevAndrey** [comment]
Cool, but is there any way to do multipart chunked transfering without loading the whole file into memory?

**Comment by koush** [comment]
If you have a file, just use that as the multipart. If you don't have a file, you'll need to implement your own Part that comes from memory/file based...
