### ISSUE TITLE
Support UTF-8

### ISSUE THREAD

**Issue by daimonkor** [koush/ion#457]
Please fix load strings

http://prntscr.com/5r40bj

Future<String> string = Ion.with(AppManager.getContext())
                    .load("http://worldoftanks.ru/ru/rss/news/")
                    .asString();
            String xml = string.get();

There are problems http://prntscr.com/5r41p5 

Android Studio 1.0.2
Gradle 2.2.1

added library with help gradle

Thanks.

**Comment by koush** [comment]
This is working as intended:

```
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 12 Jan 2015 07:46:36 GMT
Content-Type: text/xml
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
P3P: CP="ALL ADM DEV PSAi COM OUR OTRo STP IND ONL"
Content-Language: ru
Content-Encoding: gzip
```


Notice that there is no charset specified. That means the default charset is US-ASCII.
https://www.ietf.org/rfc/rfc3023.txt

I know that others have hit this issue. I can add a parameter to override the charset I guess.

**Comment by daimonkor** [comment]
Ok, but when I use 
URLConnection con = new URL(url).openConnection();
con.setReadTimeout(NewsParser.TIMEOUT);
con.setConnectTimeout (NewsParser.TIMEOUT);
this.doc = Jsoup.parse(con.getInputStream(), "UTF-8", "").normalise();

It works normal, please add parameter encoding (default 'utf-8'). Thanks for your support.

**Comment by koush** [comment]
default will never be utf8, as that is not the default in the rfc. I'll make a parameter though on asString, etc.

**Comment by daimonkor** [comment]
pleaase create parameter on asString, thanks

**Comment by megreen** [comment]
Yup, it would be awesome. When can we expect some update on this?

**Comment by koush** [comment]
1f1106b

**Comment by iNdieboyjeff** [comment]
Is this available in a Gradle version?

**Comment by koush** [comment]
Not yet. Will do another release tonight
