### ISSUE TITLE
ClassNotFoundException when using the ion library with Android Eclipse project

### ISSUE THREAD

**Issue by larrytech7** [koush/ion#458]
i have downloaded and added the libraries to my project in eclipse. the two jars(async dependency  and ion) have been added very well to the project but when the operation i try to use the library to load a remote image into an image view, i get a class not found exception telling me that the Ion class could not be found and related stuff. Below shows the exact code that i add to my onResume method is android:
All the necessary local resources(imageView, url, drawables) are ok so just look at how the class Ion colud not be found.

Ion.with(myImageView)
.placeholder(R.drawable.demoPlaceholder)
.error(R.drawable.error_image)
.animateLoad(spinAnimation)
.animateIn(fadeInAnimation)
.load("http://ubconnect.webatu.com/images/demo.png");

I need help on this issue please and fast. i will be gratefull for all the help i can get.

**Comment by koush** [comment]
I'll need a call stack...

**Comment by larrytech7** [comment]
Thanks for signalling. Here's the log dumped from the logcat. It occurs just were we have the the code i pasted in the initial post and in subsequent sections of the code that depend on it. and like i said earlier, the library has been correctly imported as well as its dependency and there is no syntax error in the code.

01-12 06:15:59.742: E/AndroidRuntime(1088): FATAL EXCEPTION: main
01-12 06:15:59.742: E/AndroidRuntime(1088): Process: larrytech.ireporter, PID: 1088
01-12 06:15:59.742: E/AndroidRuntime(1088): java.lang.NoClassDefFoundError: com.koushikdutta.ion.Ion
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at larrytech.ireporterpro.IReporterActivity.updateContent(IReporterActivity.java:757)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at larrytech.ireporterpro.IReporterActivity$LoadStreams.onPostExecute(IReporterActivity.java:903)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at larrytech.ireporterpro.IReporterActivity$LoadStreams.onPostExecute(IReporterActivity.java:1)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at android.os.Looper.loop(Looper.java:136)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
01-12 06:15:59.742: E/AndroidRuntime(1088): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by chandranshu12** [comment]
This is not a ClassNotFoundException. The NoClassDefFoundError is an error thrown by the VM at the execution time since it could not find the required class. The code is compiling correctly in Eclipse because your dependency import is correct. On the other hand, the APK you are building is not including the necessary JARs.

To fix this, go to Project -> Properties -> Java Build Path -> Libraries in Eclipse. Click on Android Private Libraries and check that the dependencies have been imported there. If you don't find them there, add them using the buttons on the right hand side. Hopefully, that should fix it for you.

**Comment by larrytech7** [comment]
Thanks for the directives.
Now , the app does not crash but doesn't load the image either. here
is the log recorded when it tries to execute:

01-27 10:25:45.458: I/AndroidRuntime(4736): VM exiting with result
code 0, cleanup skipped.
01-27 10:25:45.718: I/dalvikvm-heap(4770): Grow heap (frag case) to
12.486MB for 6123552-byte allocation
01-27 10:25:46.118: E/dalvikvm(4770): Could not find class
'com.google.gson.Gson', referenced from method
com.koushikdutta.ion.Ion$Config.getGson
01-27 10:25:46.118: W/dalvikvm(4770): VFY: unable to resolve
new-instance 520 (Lcom/google/gson/Gson;) in
Lcom/koushikdutta/ion/Ion$Config;
01-27 10:25:46.118: D/dalvikvm(4770): VFY: replacing opcode 0x22 at 0x0009
01-27 10:25:46.118: W/dalvikvm(4770): VFY: unable to find class
referenced in signature (Lcom/google/gson/Gson;)
01-27 10:25:46.118: W/dalvikvm(4770): VFY: unable to find class
referenced in signature (Lcom/google/gson/Gson;)
01-27 10:25:46.118: D/dalvikvm(4770): DexOpt: unable to opt direct
call 0x0dc7 at 0x0b in Lcom/koushikdutta/ion/Ion$Config;.getGson
01-27 10:25:46.178: D/Service(4770): Service constructed
01-27 10:25:46.249: D/libEGL(4770): loaded /system/lib/egl/libEGL_MRVL.so
01-27 10:25:46.259: D/libEGL(4770): loaded /system/lib/egl/libGLESv1_CM_MRVL.so
01-27 10:25:46.309: D/libEGL(4770): loaded /system/lib/egl/libGLESv2_MRVL.so
01-27 10:25:46.339: D/GC(4770): <tid=4770> OES20 ===> GC Version   :
GC Ver rls_pxa988_KK44_GC13.25
01-27 10:25:46.369: D/OpenGLRenderer(4770): Enabling debug mode 0
01-27 10:25:46.379: D/alarm(4770): GiftedMom periodic Check
01-27 10:25:46.589: D/dalvikvm(4770): Trying to load lib
/data/app-lib/com.polabs.demo-27/libgmscore.so 0x42af8cc8
01-27 10:25:46.589: E/dalvikvm(4770):
dlopen("/data/app-lib/com.polabs.demo-27/libgmscore.so") failed:
dlopen failed: library
"/data/app-lib/com.polabs.demo-27/libgmscore.so" not found
01-27 10:25:46.589: E/ProviderInstaller(4770): Unable to load native
code from /data/app-lib/com.polabs.demo-27/libgmscore.so
01-27 10:25:46.589: D/dalvikvm(4770): Trying to load lib
/data/app-lib/com.google.android.gms-3/libgmscore.so 0x42af8cc8
01-27 10:25:46.609: D/dalvikvm(4770): Added shared lib
/data/app-lib/com.google.android.gms-3/libgmscore.so 0x42af8cc8
01-27 10:25:46.609: D/dalvikvm(4770): No JNI_OnLoad found in
/data/app-lib/com.google.android.gms-3/libgmscore.so 0x42af8cc8,
skipping init
01-27 10:25:46.609: E/ProviderInstaller(4770): libgmscore version
mismatch (0 vs. 6599)


2015-01-27 9:09 UTC+01:00, chandranshu12 <notifications@github.com>:
> This is not a ClassNotFoundException. The NoClassDefFoundError is an error
> thrown by the VM at the execution time since it could not find the required
> class. The code is compiling correctly in Eclipse because your dependency
> import is correct. On the other hand, the APK you are building is not
> including the necessary JARs.
>
> To fix this, go to Project -> Properties -> Java Build Path -> Libraries in
> Eclipse. Click on Android Private Libraries and check that the dependencies
> have been imported there. If you don't find them there, add them using the
> buttons on the right hand side. Hopefully, that should fix it for you.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/koush/ion/issues/458#issuecomment-71605841


-- 
*Akah Larry N.H*

*Lead Software Engineer @ GiftedMom*
*Software Engineer @ IceTech Corp*
*Web And Mobile Software Developer*

**Comment by chandranshu12** [comment]
Glad to know that it helped. The key line in your stack trace is this one:

> 01-27 10:25:46.118: E/dalvikvm(4770): Could not find class
'com.google.gson.Gson', referenced from method
com.koushikdutta.ion.Ion$Config.getGson

As indicated by the VM, you don't have the Gson jar in your APK. If you have added it in your eclipse project already, you should again go and check in Java Build Path whether they are available to your APK.

BTW, you should mark this issue as resolved since your problems have nothing to do with Ion. These are generic problems you have with your set up and the ADT group or SO are the right place to ask these.

**Comment by koush** [comment]
Correct, add the gson dependency

**Comment by larrytech7** [comment]
Hello, please I need help with sending a  post request to my php server
such that I could read it as $_POST['data']. From what our given on the
github page , I don't quite understand how my script responds to such a
request .
Thanks

**Comment by larrytech7** [comment]
I could also send the data as a json, but I need to understand how my
script responds or how it reads the requests .
Thanks

**Comment by gloffreda** [comment]
Having this issue when trying using post method. 
Any help ?

Thanks

Ion.with(getApplicationContext())
                        .load("http://apidflash.sparkgo.cc/users/login")
                        .setBodyParameter("userName", mEmail)
                        .setBodyParameter("passWord", mPassword)
                        .asJsonObject()
                        .setCallback(new FutureCallback<JsonObject>() {
                            @Override
                            public void onCompleted(Exception e, JsonObject result) {
                                // Result

                                try {
                                    if (result.get("error").toString().equalsIgnoreCase("false")) {
                                        finish();
                                        Intent i = new Intent(getApplicationContext(), MainActivity.class);
                                        startActivity(i);
                                    } else {
                                        // Result is NOT "OK"
                                        String error = result.get("message").toString();
                                        Toast.makeText(getApplicationContext(), error, Toast.LENGTH_LONG).show(); // This will show the user what went wrong with a toast
                                    }
                                } catch (Exception Je) {
                                    // This method will run if something goes wrong with the json, like a typo to the json-key or a broken JSON.

                                    Log.e("ERRORCON", Log.getStackTraceString(Je));
                                }

                            }
                        });

12-21 17:34:29.611 18077-18758/com.spark.displaytrack I/dalvikvm: Failed resolving Lcom/koushikdutta/ion/Ion$Config$1; interface 9391 'Lcom/koushikdutta/ion/loader/AsyncHttpRequestFactory;'
12-21 17:34:29.611 18077-18758/com.spark.displaytrack W/dalvikvm: Link of class 'Lcom/koushikdutta/ion/Ion$Config$1;' failed
12-21 17:34:29.621 18077-18758/com.spark.displaytrack D/dalvikvm: DexOpt: unable to opt direct call 0xf3bb at 0x07 in Lcom/koushikdutta/ion/Ion$Config;.<init>
12-21 17:34:29.621 18077-18758/com.spark.displaytrack W/dalvikvm: threadid=13: thread exiting with uncaught exception (group=0x4162ac08)
12-21 17:34:29.771 18077-18758/com.spark.displaytrack E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                        Process: com.spark.displaytrack, PID: 18077
                                                                        java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:841)
                                                                         Caused by: java.lang.NoClassDefFoundError: com.koushikdutta.ion.Ion$Config$1
                                                                            at com.koushikdutta.ion.Ion$Config.<init>(Ion.java:556)
                                                                            at com.koushikdutta.ion.Ion.<init>(Ion.java:146)
                                                                            at com.koushikdutta.ion.Ion.getInstance(Ion.java:114)
                                                                            at com.koushikdutta.ion.Ion.getDefault(Ion.java:100)
                                                                            at com.koushikdutta.ion.Ion.with(Ion.java:72)
                                                                            at com.spark.displaytrack.LoginActivity$UserLoginTask.doInBackground(LoginActivity.java:344)
                                                                            at com.spark.displaytrack.LoginActivity$UserLoginTask.doInBackground(LoginActivity.java:329)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                            at java.lang.Thread.run(Thread.java:841)
