### ISSUE TITLE
Ion ver from 'com.koushikdutta.ion:ion:2.+' contains VIRUS!

### ISSUE THREAD

**Issue by favn1585** [koush/ion#459]
Checked by AVAST. Virus: SMS-AGENT.

**Comment by favn1585** [comment]
jars are generate this virus also! Shame! I will never use this library!

**Comment by koush** [comment]
huh? What are you scanning?

The library is open source, so the only way the library could be infected is my build machine had a compromised compiler. Which I really doubt.

**Comment by favn1585** [comment]
Strange but everything ok, before I build app. And I got issue in dex files only after building and only with ION. After I deleting ION lib and rebuilding, everything is ok

**Comment by koush** [comment]
What is reporting a virus? Can you send a screenshot or something?

**Comment by favn1585** [comment]
I found that this issue appears only after adding ION to project

![untitled](https://cloud.githubusercontent.com/assets/3111598/5700000/8352c79a-9a3d-11e4-80f0-5f37eb2a0f0d.png)

**Comment by favn1585** [comment]
All other libs (I got a lot) works fine

**Comment by koush** [comment]
I think this is a false positive. Besides, stuff like Play store have way more advanced threat detection built in to handle malware in APKs.

**Comment by favn1585** [comment]
This is the issue. App was on google play and users start to report this. Mobile virus (avast) also see this issue in the app.

**Comment by koush** [comment]
I just scanned all my apps which use ion (2.0.4) and did not receive this message. It is likely it is either

1) a false positive
2) there is a virus, and it is being injected on your build, during the conversion from jar to dex. I am only shipping a jar. the virus was was "detected" in the dex.

**Comment by koush** [comment]
Feel free to download AllCast from the play store and check for viruses.

**Comment by favn1585** [comment]
Looks like this is avast issue. Will write to avast support

**Comment by E3V3A** [comment]
Avast is just the most horrible AV you can use. It has messed up my system on several occasions. Instead check your files with Virus Total.
