### ISSUE TITLE
How to provide custom cache key for image caching

### ISSUE THREAD

**Issue by rahulgautam** [koush/ion#460]
In the case of amazon s3 secured url, where the actual URL for image needs to be generated and has a different value each time.

How can we achieve that with ion ?

@koush Thanks for sharing this libarary :+1: , I found bitmap handling in **ion** very awesome while image loading.

**Comment by rahulgautam** [comment]
@koush is there any follow up with this ?

**Comment by koush** [comment]
I dont understand the issue?

**Comment by rahulgautam** [comment]
Sorry about that,

In case of a S3 secured URL for an image
The actual image URL looks like this https://s3.amazonaws.com/temp-bucket-name/this.png
But if we can't use that URL as its secured and require auth.
And with auth information the URL turns into something like this 
https://s3.amazonaws.com/temp-bucket-name/this.png?X-Amz-Date=20150115T154230Z&X-Amz-Expires=300&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Signature=<SINGNATURE>&X-Amz-Credential=<CREDS>/20150115/us-east-1/s3/aws4_request&X-Amz-SignedHeaders=Host&x-amz-security-token=<SECURITY_TOKEN>

That is valid for a moment and can be used to download the image, But we can not use this for caching because there is no way for app to create that same URL again to retrieve the image from cache.

So I am saying there could be either two way to achieve this fuctionality

1. 
I load image using this auth-url (mumbozombo) with ion, but ion provides a method that can be override or globally, by using that I can modify the cache, 
So what would happen is that ion internally called a getCacheKey() here the implementation would be mine, here I can trunc that whole auth part from url and return the key by checking it.
That fullfil my image caching need for these url.

2. 
ion provides a method to convert the URL before sending a request using that, so here one can convert the url to this mumbozumbo url and ion uses cache by the first provided url.

Don't know if this explains, For inspiration Please look at this iOS library implementation, here is how it supports this https://github.com/rs/SDWebImage#using-cache-key-filter

Thanks for your time

**Comment by rahulgautam** [comment]
Another Simplest way would be, Rather than using the the whole URI (`scheme://host/path?query_paramters`) as part of the key, **Ion** should *not* use `query_paramater` as part of key.

It should ony use `scheme://host/path`.

Is this can be done easily? @koush Please way in.

**Comment by rahulgautam** [comment]
Hi @koush 

Will you please look at my comments? Please let me know if still issue does not clarify itself.

Thanks

**Comment by rahulgautam** [comment]
@koush anything you can help :8ball:

**Comment by koush** [comment]
You could use headers instead of query strings on the s3 url authentication.

http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html

**Comment by rahulgautam** [comment]
Thanks @koush ,
If we do so, how one can provide auth header to *ion* for the url it is going to download.

**Comment by rahulgautam** [comment]
Got it.

```
Ion.with(imageView)
.placeholder(R.drawable.placeholder_image)
.error(R.drawable.error_image)
.animateLoad(spinAnimation)
.animateIn(fadeInAnimation)
.load("http://example.com/image.png")
.setHeader("cache-control", "max-age=180");
```

**Comment by koush** [comment]
Huh? That shouldn't even compile.

Ion.with(context)
.load("http://example.com/image.png")
.setHeader("cache-control", "max-age=180");
.withBitmap()
.placeholder(R.drawable.placeholder_image)
.error(R.drawable.error_image)
.animateLoad(spinAnimation)
.animateIn(fadeInAnimation)
.intoImageView(imageView);
