### ISSUE TITLE
Chunked input ended before final chunk

### ISSUE THREAD

**Issue by astinx** [koush/ion#463]
Hi there, I'm having the following issue; Only with certain kind of requests, the library returns this error.

"com.koushikdutta.async.http.filter.ChunkedDataException: chunked input ended before final chunk"

This certain kind of request, are actually json responses from the server that are pretty large. I tried making this request with curl in the terminal and It's returning the following.

 curl  -X GET  -d '{"profile_id":"60","user_id":"58", "social_network_id":1}' http://minikast.dev3/test/getProfileInfo

{"profile_id":"1", ........ (18) transfer closed with outstanding read data remaining .... }

I mean, in the middle of the response seems to had been cutted off. But if I send the request in this way:

curl --http1.0  -X GET  -d '{"profile_id":"60","user_id":"58", "social_network_id":1}' http://minikast.dev3/test/getProfileInfo

Everything works fine, (I think that is because in HTTP/1.0 there are not chunked request). So my question is: Can I change the request that Ion is doing from HTTP/1.1 to HTTP/1.0? Has the API some method to do this?

Thanks!, awesome library, this is the third project in wich I use it.

**Comment by koush** [comment]
Well, since curl is failing too (using http1.1 by default), with the exact same error, then it's likely an issue with your server.

You could try using .header("Connection", "close")

that often allows content encoding fallback to http 1.0 behavior, and disables chunked responses.

There's currently no way to fall back to http 1.0 in ion though.

**Comment by astinx** [comment]
Thanks for your anwert but using addHeader("Connection", "close") didn't work. Maybe I can checkout your code and change it to made the request through HTTP/1.0?. Or you are using some lib like Apache commons and doesnt allow that?

**Comment by koush** [comment]
yeah can check out androidasync and ion and change it. youre probably better off fixing that server though.
