### ISSUE TITLE
Flickering while reloading ImageView url

### ISSUE THREAD

**Issue by dominolog** [koush/ion#468]
Hi

There is an issue while reloading ImageView bitmap. I call load into ImageView twice. 1st load loads the image and caches it. Problem is the default drawable is displayed always, even if the image is in local cache which results in flickering. Could the ION forward displaying default drawable after the image is checked against in-cache existence?

**Comment by koush** [comment]
code sample? How is the default drawable specified? Local cache is still in the file system, so there is going to be a load time. Ion will not load cached local images synchronously on the UI thread.

The only time ion will load an image synchronously is if it is in memory already.

**Comment by dominolog** [comment]
Hi

Below is a video showing described issue. 
https://plus.google.com/photos/yourphotos?pid=6107528462055800882&oid=105481744367437200305

I load images by calling Ion this way:

@Override
	public void loadImage(Uri uri, ImageView imageView, boolean doCrop,
			int placeholderImageId, int errorImageId,
			final ImageLoaderListener listener) {
		
		//.addHeaders(mRequestHeaders)
		BF<? extends BF<?>> b = Ion.with(mContext)
			.load(uri.toString())
			.addHeaders(mRequestHeaders)
			.withBitmap();
		if (doCrop) {
			b = b.centerCrop();
		}
		
		b.placeholder(placeholderImageId)
			.error(errorImageId)
			.fadeIn(true)
			.intoImageView(imageView)
			.setCallback(new FutureCallback<ImageView>() {

					@Override
					public void onCompleted(Exception ex, ImageView arg1) {
						if (listener != null) {
							if (ex == null) {
								listener.onImageLoadSuccess(null);
							} else {
								listener.onImageLoadError();
							}
						}

					}
				});
	}

**Comment by koush** [comment]
video link does not work.

**Comment by koush** [comment]
i think you may just want to use .crossfade(true)
