### ISSUE TITLE
Image turns sideways when loaded with cross fade and deep zoom

### ISSUE THREAD

**Issue by afollestad** [koush/ion#470]
A user of my app (in alpha stages) reported that an image appears normally as a thumbnail, and turns sideways when opened in full screen.

This is a sample image that was provided, and I'm able to reproduce the issue: https://docs.google.com/file/d/0B0SyrkOO1ZHPUC05eVdsNzRBY1k/edit?usp=docslist_api

When in full screen, cross fade is used (to transition from the thumbnail to the fully loaded image), along with deep zoom.

He also told me that the image was taking using the Samsung camera, not sure if there's any meta data in there (like orientation) that would cause this to happen.

**Comment by afollestad** [comment]
I can confirm that this is a deep zoom issue: the problem goes away when deep zoom is disabled.

**Comment by koush** [comment]
Yeah, this is a deep zoom issue in that it does not respect hte exif rotation tag

**Comment by koush** [comment]
dupe #430
