### ISSUE TITLE
Disable redirection

### ISSUE THREAD

**Issue by Gnzlt** [koush/ion#471]
I can not find a way to disable redirection when using Ion. The problem is that I need headers from the first response, not the redirected one. Specifically the "Location" tag from the first response.

Is there any way to solve that?

Thanks

**Comment by koush** [comment]
```java
.folowRedirect(false)
```

https://github.com/koush/ion/blob/master/ion/src/com/koushikdutta/ion/builder/RequestBuilder.java#L134
