### ISSUE TITLE
Problem with caching.

### ISSUE THREAD

**Issue by alexandrius** [koush/ion#472]
Hello I get "Response is not cacheable".
I think problem is in the request header:

"Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Type: text/html
Date: Sat, 24 Jan 2015 18:55:10 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: Apache
Set-Cookie: site=afe9b204a0e87fa31af69648f390f721; path=/, site_clang=en; expires=Tue, 19-Jan-2016 18:55:10 GMT; path=/
Transfer-Encoding: chunked
X-Powered-By: PHP/5.4.35"

**Comment by koush** [comment]
That is the response header. The response is not cacheable.
