### ISSUE TITLE
Store (persistent) cache not used

### ISSUE THREAD

**Issue by norman-kapschefsky** [koush/ion#474]
Hi,
first of all I would like to thank you for this great library. I used UrlImageViewHelper before and now updated to Ion. Due to this there are some issues I cant figure out. I use Ion for requesting images from http and I want to cache them permanently (until they are touched). But only the response cache (getCache()) is used and not the permanant cache (getStore()). How do I get it to operate?

In addition is it possible to define the caching time intervall somewhere like in the old UrlImageViewHelper library? I tried this on my own but when getting the file from cache it is automatically touched by your lib so that lastModified() of file is overwritten.

Thanks in advance.

**Comment by koush** [comment]
You can increase the response cache size to an infinite value. Or something reasonably larger.
