### ISSUE TITLE
SSL hang?

### ISSUE THREAD

**Issue by schwiz** [koush/ion#475]
Using 2.0.2 I have no way to reproduce this issue reliably but occasionally my requests will never return, the callback nor timeout is not honored.

I see in the verbose logs socket connected, after 64 seconds (timeout set to 8 seconds via setTimeout api on builder) the logs spit out: (64710 ms) https://api-qa.starshop.com/rest/featured: closing out socket (exception) and my callback is never called.

I did notice an update fixing 'SSL hang' and I have updated my build script to now use 2.0.5  Does this sound like a symptom of the issue fixed in 2.0.4 or something else?

**Comment by koush** [comment]
Yeah, I think this was fixed in 204/205. SPDY issue if I recall.

**Comment by koush** [comment]
https://github.com/koush/AndroidAsync/commit/8fccb744e3661434fafafc4c80e0ba8999a169d5

**Comment by koush** [comment]
Oh, occurred even if spdy was not supported. Was an SSL regression with the SPDY implementation.

**Comment by schwiz** [comment]
Thanks!
