### ISSUE TITLE
Having trouble loading/importing the sample app, :ion:ion could not be found

### ISSUE THREAD

**Issue by Moter8** [koush/ion#477]
![1](http://i.imgur.com/h6nSjEm.png)

First it nags me about the Gradle Home which I apparently have to point at the binaries and after that it shows me this popup?

**Comment by koush** [comment]
it tries to load the source based ion library (instead of maven). You will need to check out ion into your project root, and include not only the sample, but also ion's library itself (and AndroidAsync as well).

Alternatively, just modify the build.gradle to pull the ion library from maven.
