### ISSUE TITLE
What makes ion send an exception to onCompleted()?

### ISSUE THREAD

**Issue by CTassisF** [koush/ion#478]
I'm using ion to fetch an URL but even when this URL returns "HTTP/1.1 500 Internal Server Error" it does not send exception to onCompleted().
What makes ion send an exception to onCompleted()? Shouldn't it also fail on errors 4XX/5XX?

Thanks in advance.

**Comment by CTassisF** [comment]
In addition I am seeing "[ 01-31 20:06:38.269  6796: 6796 W/art ] Attempt to remove local handle scope entry from IRT, ignoring" in result when the error 500 happens, but I think this is a Lollipop issue.

**Comment by koush** [comment]
Ion will only send exceptions if there is an actual protocol error. Ie, malformed json, connection is closed, etc.

If you need to check the response code, use .withResponse()

**Comment by koush** [comment]
This is because rest services will often return JSON along with their 4xx or 5xx error.
