### ISSUE TITLE
Image flashing while reloading

### ISSUE THREAD

**Issue by meraklis56** [koush/ion#479]
I want Ion to download every 0.5 sec to download an image and apply it to an imageview. Like a live-feed.
The only problem is that for a considerable amount the imageview is white. I tried to disable .tobitmap() for this command but there was no success. Is there anyway leave the imageview the same until the new image comes?

the command:
Ion.with(getApplicationContext()).load(link).noCache().withBitmap().intoImageView(iv);

**Comment by koush** [comment]
try using .crossfade()

**Comment by meraklis56** [comment]
I tried:
Ion.with(iv).crossfade(true).load(link);
but the image wasn't refreshing due to cache. I deleted the whole cache, the white image is still there

Then, i tried with the other way
Ion.with(getApplicationContext()).load(link).noCache().withBitmap().crossfade(true).intoImageView(iv);

and i got force close:
"java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.koushikdutta.ion.ContextReference$ImageViewContextReference.get()' on a null object reference"

Why is it happening?

**Comment by koush** [comment]
null pointer is fixed with e8a40a27ae125f29d1fb017462215923c39e7b2e

That may also fix your issue with crossfade.

**Comment by asker517** [comment]
@koush still not work
