### ISSUE TITLE
Question about the lrucache and jpegs

### ISSUE THREAD

**Issue by alaeri** [koush/ion#48]
Would it be a good idea to keep in the lrucache bytearrays of jpegs and  a small cache of bitmaps?

It would often remove the disk access and would increase the cache size by tenfold.

The limitations that would occur would be a reduced size of the bitmap cache and more cpu intensive operations in order to redecode the bitmaps.

What do you think? Would it be too long to redecode? Im wondering if it could be the silver bullet for my case (full width pictures).

**Comment by koush** [comment]
there's a transform cache now
