### ISSUE TITLE
Header NewLine Issue

### ISSUE THREAD

**Issue by Spoetnic** [koush/ion#483]
Hey Koush, 

I stumbled upon an uncaught issue with the way ION handles headers.

I generated an authentication String, which happened to end with a LineFeed character (10), by the following code:
<B>.addHeader("Athentication", "someAuthenticationEndingWithANewLineCharacter")

This resulted in all the following headers to be dropped, as well as the body that I tried to send with it. Making it impossible for the server to check my authentication, since the body was used to generate it.
IMHO, this should be caught by ion :p (maybe throw and Exception)

**Comment by Spoetnic** [comment]
Also, ion version 2.0.5

**Comment by koush** [comment]
https://github.com/koush/AndroidAsync/commit/b7113268d17513fb1dbe05a7315c836490180194
