### ISSUE TITLE
"with" method don't accepts parameters as described.

### ISSUE THREAD

**Issue by DeekshithRamamoolya** [koush/ion#490]
The document provided by you describes with method accepts context and url,But  its not working in code (in updated library 2.0.6).
For previous version(1.1.5) its works fine , but in updated version i'm not able to see with(context, string) method. You could have deprecated it but its seems to removed.
![issue](https://cloud.githubusercontent.com/assets/11056589/6243903/62bb463c-b771-11e4-926e-91eb32288cd4.png)

**Comment by koush** [comment]
use .with(context).load(url).

**Comment by DeekshithRamamoolya** [comment]
thank you.
