### ISSUE TITLE
Proxy server! It show logs by default!

### ISSUE THREAD

**Issue by IRMobydick** [koush/ion#491]
Hi Koush,
As I know in my app, I did not enabled proxy configuration, But in "Fiddler" I can see logging. I'm using the latest version of Ion!
Is it changed in latest version?
How can disabled it or be sure that this feature is disable?

Thanks Man

**Comment by koush** [comment]
Did you set up a global proxy server in your android config? Or leave it enabled somewhere?

**Comment by IRMobydick** [comment]
Did not, I almost sure.
Is there a way to disable it totally?

**Comment by koush** [comment]
Not sure. There's no bug here. The only way ion can use a proxy is if you somehow provided it with the proxy settings. It's not going to pull those settings out of thin air :)

**Comment by IRMobydick** [comment]
Thanks, But you know what...
I can see Ion requests to server by sniffing it in various networks. It's just need to set my device Wifi proxy hostname and proxy port ( for example 192.168.1.30 | 8888) and Bingo! All requests can be sniff :(

as I read in Ion ReadMe, for something like that I should setup proxy setting for Ion! to Ion show these for that special proxy! but now, I can see requests without proxy setting for Ion on All Networks!

I'm using of Ion from version 1, And on that version this features works as a charm! but in new version ( specially after version 1.0.3), It happen as described above :(

I love Ion, And want it
Thanks for that Koush

**Comment by IRMobydick** [comment]
@koush Is there any way to set ion don't use that global proxy? for example set fake proxy for ion?
