### ISSUE TITLE
Out of memory when load as bitmap

### ISSUE THREAD

**Issue by andj207** [koush/ion#492]
Hello,

I've got this error exception when trying to load this bitmap at http://ichef.bbci.co.uk/podcasts/artwork/tae.jpg. I know it's because the bitmap file is too big 1400x1400. I would suggest that the builder is better if it has a subsample option.

The stacktrace is below:

    02-18 11:59:54.311    2941-2978/? E/dalvikvm-heap﹕ Out of memory on a 83236-byte allocation.
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ "ion-ion" prio=5 tid=17 RUNNABLE
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0xa6d6ab10 self=0xb7f9bea8
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ | sysTid=2978 nice=0 sched=3/0 cgrp=[fopen-error:2] handle=-1209809424
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ | schedstat=( 423634404 132092296 373 ) utm=36 stm=5 core=0
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:~48)
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ at java.nio.ReadWriteHeapByteBuffer.<init>(ReadWriteHeapByteBuffer.java:49)
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ at java.nio.ByteBuffer.allocate(ByteBuffer.java:52)
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ at com.koushikdutta.async.ByteBufferList.obtain(ByteBufferList.java:504)
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ at com.koushikdutta.async.util.Allocator.allocate(Allocator.java:28)
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ at com.koushikdutta.async.util.Allocator.allocate(Allocator.java:24)
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:124)
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
    02-18 11:59:54.311    2941-2978/? I/dalvikvm﹕ [ 02-18 11:59:54.315  2941: 2978 W/dalvikvm ]
    threadid=17: thread exiting with uncaught exception (group=0xa625d288)

**Comment by koush** [comment]
Use resize to size the image to something manageable.

Or use deepZoom for large bitmaps.

**Comment by andj207** [comment]
Thanks @koush! My bad I forgot the resize feature :)
