### ISSUE TITLE
Url is correct but its not loading image without http:// protocol

### ISSUE THREAD

**Issue by prashantwosti** [koush/ion#493]
Try loading this with ION

http://image.tmdb.org/t/p/w500/eobmLyrH2DRMZI0K1BijLjc7HD4.jpg

here url resolves and wipes http:// protocol resulting image fail to load.

and then try loading 

https://d13yacurqjgara.cloudfront.net/users/559591/screenshots/1857353/christmas_tubik__1x.jpg

this loads fine. 

Why is that? I tried this with picasso too. encountered same issue.

sorry if this issue is already addressed but I didn't find while searching.

**Comment by koush** [comment]
works fine.
