### ISSUE TITLE
Group for ImageView request

### ISSUE THREAD

**Issue by pierrre** [koush/ion#494]
How to set a group for an ImageView request?

I want to cancel all ImageView request if my Activity/Fragment is closed.

**Comment by schwiz** [comment]
https://github.com/koush/ion#request-groups

**Comment by koush** [comment]
You don't need to manage this. Ion does that automatically.

**Comment by koush** [comment]
Ion.with(activity) and .with(fragment) watch for the lifecycle events.

**Comment by pierrre** [comment]
OK thank you! :+1

Is there something in your documentation about it?

**Comment by koush** [comment]
Should be in the readme
