### ISSUE TITLE
Bug UTF-8 Support

### ISSUE THREAD

**Issue by daimonkor** [koush/ion#496]
```java
 Future<String> string = Ion.with(AppManager.getContext())
                    .load(url)
                    .asString(Charsets.UTF_8);
```
http://worldoftanks.ru/ru/rss/news/
![image](http://i.imgur.com/ufH7Oc1.png)
Thanks for your support.

**Comment by koush** [comment]
is that the url i can test against?

**Comment by daimonkor** [comment]
I use Android Studio 1.1.0
I cleared project, built again and problem reproduced
```  compile 'com.koushikdutta.ion:ion:2.+'```

**Comment by koush** [comment]
What url can I test against?

**Comment by daimonkor** [comment]
yes, please

**Comment by koush** [comment]
You need to give me a test url.

**Comment by koush** [comment]
Give me a http link with the ion code I can use to run a test to reproduce this bug.

**Comment by daimonkor** [comment]
Future<String> string = Ion.with(AppManager.getContext())
                    .load("http://worldoftanks.ru/ru/rss/news/")
                    .asString(Charsets.UTF_8);

**Comment by daimonkor** [comment]
I used Gradle, cleaned project, built again, bug reproduced.

**Comment by koush** [comment]
I have not published the fix yet. You'll need to checkout and build using master.

**Comment by daimonkor** [comment]
Ok, I will wait gradle version, thanks)
