### ISSUE TITLE
Issues with transparent GIFs, and GIFs in general

### ISSUE THREAD

**Issue by afollestad** [koush/ion#506]
**I have a screen capture to aid in describing what I mean:** http://youtu.be/Ckfo0CyeCkk

## Related to Transparent GIFs
 
It looks like the first frame of the GIF gets stuck in the background, as if the layer gets stuck there and doesn't change visibility.

## Related to GIFs in General

It appears that if a GIF is already playing in an ImageView, and you attempt to load/play the GIF again, the GIF plays very fast (or plays over the initial one). The video shows this when my app's activity resumes.

**Comment by koush** [comment]
Oh I know what's wrong. Link to image please?

**Comment by afollestad** [comment]
@koush it actually happens to be the first one returned by Googling "gif" haha:

http://cdn.osxdaily.com/wp-content/uploads/2013/07/dancing-banana.gif

**Comment by koush** [comment]
ok both fixed, will release soon.

**Comment by afollestad** [comment]
Thank you!
