### ISSUE TITLE
Embed network exceptions in response object

### ISSUE THREAD

**Issue by HishamGhosheh** [koush/ion#509]
We added a top level AsyncParser to parse all responses

```java
public class ApiResponseParser<T> implements AsyncParser<ApiResponse<T>> { .. }
```

```java
Ion.with(context).load("GET", url).as(new ApiResponseParser()).setCallback(new FutureCallback<ApiResponse>() {
            @Override
            public void onCompleted(Exception e, ApiResponse result) {
// we ignore Exception e
// we test result,isSuccess();
}
};
```

The ApiResponse will have a result object along with an exception (if any).
Now in case there's no connection available: e = exception, result = null

What we want to do is to receive a "result" object in the previous onCompleted callback even if a network isn't available.
It will mainly be a dummy response holding the network exception

We tried inserting a SImpleMiddleware but apparently that will only allow us to modify headers.
We couldn't figure how to do it using a custom HttpLoader either.

The only workaround now is to check the returned exception in all of our callbacks.

Can you please guide us on how to achieve this to maintain our code flow?

**Comment by koush** [comment]
```java
abstract class CustomFutureCallback implements FutureCallback<ApiResponse> {
  @Override
  public void onCompleted(Exception e, ApiResponse result) {
    if (e != null)
      result = new ApiResponse(e);
    onCompleted(result);
  }

  abstract void onCompleted(ApiResponse result);
}

```

Then...

```java
Ion.with(context).load("GET", url).as(new ApiResponseParser()).setCallback(new  CustomFutureCallback<ApiResponse>() {
  @Override
  public void onCompleted(ApiResponse result) {
  }
};
```

**Comment by HishamGhosheh** [comment]
Thanks a lot! never came to my mind to do it in the callback itself.
And sorry if this comment triggers a notification :-)
