### ISSUE TITLE
single data only

### ISSUE THREAD

**Issue by kakkuk** [koush/ion#520]
hi, i wan to load single data but it is gives me error. can some one help me please

private void getContent(){
    	Ion.with(this)
    	.load("http://domain.com/app.json")
    	.asJsonObject()
    	.setCallback(new FutureCallback<JsonObject>() {
    	   @Override
    	    public void onCompleted(Exception e, JsonObject result) {
    		   Log.d("title: ", result.get("title").getAsString());
       	    }
    	});
    }

**Comment by kakkuk** [comment]
why closed, please can you help me how get data like above

**Comment by koush** [comment]
no log, no url.
