### ISSUE TITLE
some questions, thx~

### ISSUE THREAD

**Issue by zhaoxj** [koush/ion#521]
Hi Koush, Great library!

I have some some questions about cache:
1.I use the code;
   Ion.with(context)
        .load(url)
        .noCache()
        .asJsonObject()
        .setCallback();
    question: I find there still exist the cache file in packagename/cache/ion/.so, how to use?

2.If I want to use the cache file by url,I use the code:
   Ion.getDefault(context)
        .configure()
        .getResponseCache()
        .getFileCache()
        .get(url);
    question:I find the url is not  transformed into the cache filename, how to get the right filename by url or    
how to get the cache by url?

Your reply will be great appreciated,thank you.

**Comment by koush** [comment]
#2 is not a valid usage. Don't attempt to use the cache directly.

Even if noCache is used, the response may still be cached if a later call does not request with noCache.
