### ISSUE TITLE
Forcing ION to preload images while using a ViewPager

### ISSUE THREAD

**Issue by fbis251** [koush/ion#522]
Hey,

 As the title says I would like to force images to download when the onCreate() method is called for Fragments used in a ViewPager. This used to work before the 2.0.0 release where you added the following:

> ImageView network requests are initiated onDraw (whereas they were immediately executed before). This results in automatic prioritization of on screen vs off screen ImageViews.

Is there any way to bring the old behavior back?

EDIT

Just to clarify, what happens now is that the first 2 images will load in a ViewPager. When you swipe to the 2nd image, the 3rd image will not automatically download until you swipe to the 3rd image and the ImageView is visible on screen. Then it will download bot the 3rd and 4th images and so on.

**Comment by koush** [comment]
I prefer this new behavior as the default behavior. I suppose I could make an option to fetch immediately.

**Comment by adi1133** [comment]
You can initiate an offscreen fetch by using `imageView.draw(new Canvas())`

**Comment by fbis251** [comment]
@adi1133 thanks that's the behavior I was looking for

**Comment by adi1133** [comment]
@koush I't whould be great if I can hint to the library that that I want to load an image that is not in the foreground but it most probably will be. It should have less priority than a foreground image but more than a background one. 
The usecase I am having, is loading the images that are in a fragment that is coming up in a viewPager

**Comment by jhmacdon** [comment]
Setting your pagers offscreen max to some larger number will preload the pages.
