### ISSUE TITLE
Is it possible connect to the server with basic authentication??

### ISSUE THREAD

**Issue by Spiderbezno** [koush/ion#523]
My image is in a server with basic autentication , it is possible to add it in a header?

**Comment by koush** [comment]
use .basicAuthentication method whne building the request.

**Comment by sputhurk** [comment]
Hi,
Could you pls let me know how to use the basicAuthentication method with ion? I use the following snippet and it's giving me an error saying unable to authenticate.

Ion.with(this)
            .load("http://127.0.0.1:7101/rest/1/ListEmp)
            .basicAuthentication("user","password")
            .asJsonObject()
            .setCallback(new FutureCallback<JsonObject>() {

Any help will be appreciated.

Thanks,
Shiva
