### ISSUE TITLE
How to stop gif animation and replay the animation

### ISSUE THREAD

**Issue by uzxmx** [koush/ion#527]
I know I can use AnimateGifMode.ANIMATE_ONCE to just animate once. But how can I then replay it? Can I have a reference to control the animation at any time? I have looked through the source code, and found the animation is coded in IonDrawable.java. But because of class restriction, I cannot access it in my project. Please help me out. Thanks!

**Comment by kkm** [comment]
+1

**Comment by MeiYi2** [comment]
+1.
