### ISSUE TITLE
Charles returns 503 while sending requests over HTTP proxy without transparent proxying

### ISSUE THREAD

**Issue by tzuhsienli** [koush/ion#541]
Hi, Koush, I am developing my first android app, that uses this brilliant library on my api layer. While I test my app over the HTTP proxy server (Charles) without transparent proxying. Charles returns a 503 status code. I tracked into your code and has no any solutions for this issue, So, would you please look into this, or you must meet the same questions before, please help, if you have any suggestions.
BTW, the transparent proxying requests are working normally. 
![07b94c5b-abb8-45b2-8ce9-9893237d9134](https://cloud.githubusercontent.com/assets/1008704/7202617/a5a87426-e546-11e4-9c7b-d084ca443ab0.png)
![0f62e1a6-e5c6-49d5-9ef0-6d7c14868b9b](https://cloud.githubusercontent.com/assets/1008704/7202619/af2ec81a-e546-11e4-8c4a-74225efd8ad1.png)

**Comment by tzuhsienli** [comment]
Any comments? Thx

**Comment by koush** [comment]
Fixed here, will need to do a release.

https://github.com/koush/AndroidAsync/commit/7160cd9f8299d614e703541792d75871685bd6a8
