### ISSUE TITLE
How to form a mutliple image request dynamically?

### ISSUE THREAD

**Issue by mithrann** [koush/ion#548]
Ion.with(ProgressBarUpload.this)
                        .load(URL)
                                // attach the percentage report to a progress bar.
                                // can also attach to a ProgressDialog with progressDialog.
                        .uploadProgressBar(progressBar)
                                // callbacks on progress can happen on the UI thread
                                // via progressHandler. This is useful if you need to update a TextView.
                                // Updates to TextViews MUST happen on the UI thread.
                        .uploadProgressHandler(new ProgressCallback() {
                            @Override
                            public void onProgress(long downloaded, long total) {
                                uploadCount.setText("" + downloaded + " / " + total);
                            }
                        })
                                // write to a file
                        .setMultipartFile("uploaded_file", f)
                        .setMultipartParameter("params1", "1")
                        .asString().setCallback(new FutureCallback<String>() {
                    @Override
                    public void onCompleted(Exception e, String result) {
                        Toast.makeText(getBaseContext(), "" + result, Toast.LENGTH_SHORT).show();
                    }
                });

Here instead of just setting one image file i need to set as many as user selected(dynamically).
I know that we can add many .setMultipartFile() to a request. But how to form a request dynamically is problem. 
Thanks

**Comment by coderlin** [comment]
i have the same probrom
