### ISSUE TITLE
Caching images on sd card

### ISSUE THREAD

**Issue by amodkanthe** [koush/ion#549]
Hi,

I want to cache Image on sd card instead of memory cache.  It should first check image available in sd card or not otherwise load image from url.

I want to know is it possible using Ion library,I didn't see anything related to it in samples.

**Comment by koush** [comment]
Nope, SD card is too slow, and may disappear, etc.

**Comment by amodkanthe** [comment]
"Disk and memory caching" I saw this in library features I thought library does that. I don't want image to load again when application is re-opened in order to save apps data usage is it possible using ION along with my custom file cache

**Comment by koush** [comment]
It has a file cache stored on internal storage.

**Comment by amodkanthe** [comment]
Okay how to enable that and customize size etc. is it there in sample

**Comment by vladimirarevshatyan** [comment]
I am waiting for this to be answered....
