### ISSUE TITLE
Need an setMultipartParameterAsObject in ION

### ISSUE THREAD

**Issue by xriztot** [koush/ion#555]
Hello koush, hope you are doing good. 
Well regarding to this post this is not a issue, you can say it's an extension to ION library im wanting to, or might be i am unaware of the thing which i'm going to ask.

Im working with your library, it's pretty good and easy to make callback calls. i defined separate functions for all VERBS to re-use them in my app following is the POST function for my Multipart POST. 

        public Future<Response<JsonObject>> doMultipartPostItem(
			File itemImageFilePath, String title, String desc, String price,
			String qty, String internationalcharges, String domesticcharges,
			String state, List<Part> multiParts,
			LoginShareApplication sharedLoginPref) {
		try {

			postCallback = Ion
					.with(mContext)
					.load("POST", getCompleteUrl("storeadmins/itemsmini")) 
					.setLogging("ion-geny", Log.VERBOSE)
					.setHeader(
							"Authorization",
							sharedLoginPref.getUsername() + ":"
									+ sharedLoginPref.getPassword())
					.progressDialog(progress) 
					.setMultipartParameter("title", title)
					.setMultipartParameter("description", desc)
					.setMultipartParameter("price", price)
					.setMultipartParameter("quantity", qty)
					.setMultipartParameter("state", state)
					.setMultipartParameter("internationalcharges",
							internationalcharges)
					.setMultipartParameter("domesticcharges", domesticcharges) 
					.addMultipartParts(multiParts).asJsonObject()
					.withResponse();
		} catch (Exception ex) {
			LoginShareApplication.toast("Network Error");
		}
		return postCallback;
	}

Similarly like the above function i have simple POST function without multipart . i.e.

     public Future<Response<JsonObject>> doPost(String url,
			Object postJsonObject  ) {
		try {
			 

				postCallback = Ion
						.with(mContext)
						.load("POST", getCompleteUrl(url))
						.setLogging("ion-geny", Log.VERBOSE)
						.progressDialog(progress)
						.setHeader(
								"Authorization",
								sharedLoginPref.getUsername() + ":"
										+ sharedLoginPref.getPassword())
						.setJsonPojoBody(postJsonObject).asJsonObject()
						.withResponse();
			 
		} catch (Exception ex) {
			LoginShareApplication.toast("Network Error");
		}
		return postCallback;
	}

Now as you can see the difference, I have to pass each multipart parameters with the MultipPart file, Now what i want is to send MultiPart files as well as an whole object which automatically binds the object  with the properties to the multipart post request. Because now the problem im facing is, i have to make different functions for every multipart parameters, i cannot use it as a generic / dynamic call.

The requriement i'm wanting is : 

      public Future<Response<JsonObject>> doPost(String url,
			Object postJsonObject ,  List<Part> multiParts) {
		try {
			 
	postCallback = Ion
						.with(mContext)
						.load("POST", getCompleteUrl(url))
						.setLogging("ion-geny", Log.VERBOSE)
						.progressDialog(progress)
						.setHeader(
								"Authorization",
								sharedLoginPref.getUsername() + ":"
										+ sharedLoginPref.getPassword())
         // It's good if i setJsonPojoBody 
						.setJsonPojoBody(postJsonObject)
        // Or similar to this like 
					        .setMultipartParameterAsJson(postJsonObject)
                                                .addMultipartParts(multiParts).asJsonObject()
                                                .asJsonObject()
						.withResponse();
			 } catch (Exception ex) {
			LoginShareApplication.toast("Network Error");
		}
		return postCallback;
	}

Or if there's any alternate way to do it. Like to make just one function of Multipart with PojoBody. Let me know.

Waiting for your reply, 
Thanks.

**Comment by koush** [comment]
Quick observation, there's no reason to try/catch. Ion will never throw while building the request, unless there's a argument error in what is passed to it.

Ie, you can't "Network Error" there.

**Comment by koush** [comment]
You can't do a JSON body and a Multipart body. Only one body per post.

You may want to do your own serialization of the POJO to JSON and pass that as a multipart string. Your use case is fairly specialized, so I wouldn't be open to adding it to the library.

**Comment by xriztot** [comment]
Thanks koush, your statement "You may want to do your own serialization of the POJO to JSON and pass that as a multipart string" really helped me, lol. 

But for this i have to parse the string to JSON on server side which i was avoiding. But it works without much effort.

You are right about the try/catch as i'm already handling in the callback. 

Now following is my workout for this problem i raised.

               public Future<Response<JsonObject>> doMultipartPostWithObject(String url,
			List<Part> multiParts, Object postObj,
			LoginShareApplication sharedLoginPref) {

		Gson gson = new Gson();
		String multipartParamPojo = gson.toJson(postObj);

		if (multiParts == null) {
			postCallback = Ion
					.with(mContext)
					.load("POST", getCompleteUrl(url))
					.setLogging("ion-geny", Log.VERBOSE)
					.setHeader(
							"Authorization",
							sharedLoginPref.getUsername() + ":"
									+ sharedLoginPref.getPassword())
					.progressDialog(progress)
					.setMultipartParameter("pojo", multipartParamPojo)
					.asJsonObject().withResponse();

		} else {
			postCallback = Ion
					.with(mContext)
					.load("POST", getCompleteUrl(url))
					.setLogging("ion-geny", Log.VERBOSE)
					.setHeader(
							"Authorization",
							sharedLoginPref.getUsername() + ":"
									+ sharedLoginPref.getPassword())
					.progressDialog(progress)
					.setMultipartParameter("pojo", multipartParamPojo)
					.addMultipartParts(multiParts).asJsonObject()
					.withResponse();
		}

		return postCallback;
	}

Cheers :-)
