### ISSUE TITLE
Unable to set custom headers to request

### ISSUE THREAD

**Issue by yakubbaev** [koush/ion#561]
This is my code:
```
    void runIon(String url) {
        Ion.with(this)
                .load(url)
                .setHeader("foo", "bar")
                .asString()
                .setCallback(new FutureCallback<String>() {
                    @Override
                    public void onCompleted(Exception e, String result) {
                        System.out.println("***** Response: " + result);
                    }
                });
    }
```
Also tried addHeader, no luck. 

```
    OkHttpClient client = new OkHttpClient();

    void runOkHttp(String url) {
        Request request = new Request.Builder()
                .url(url)
                .addHeader("foo", "bar")
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Request request, IOException e) {
                e.printStackTrace();
            }

            @Override
            public void onResponse(Response response) throws IOException {
            }
        });
    }
```
The same code with OkHttp says that server receiving custom header as 
```
        "HTTP_FOO": "bar",
```

**Comment by koush** [comment]
The header is "foo" via Ion, not "HTTP_FOO". Not sure why your server is receiving it like that.

**Comment by sagarda7** [comment]
.setHeader("foo", "bar") or .addHeader("foo", "bar") is not working for me. my server is not receiving foo header.

**Comment by yakubbaev** [comment]
@sagarda7 see #562

**Comment by sagarda7** [comment]
Thanks @yakubbaev

I have fixed the problem from #562 like this

    static class IonMiddleWare extends SimpleMiddleware {
          @Override
            public void onRequest(OnRequestData data) {
                super.onRequest(data);
                data.request.setHeader("Apikey", Const.API_KEY);
            }
        }

and 

    Ion.getDefault(context).getHttpClient().insertMiddleware(new IonMiddleWare());

**Comment by koush** [comment]
I wouldn't do that for this use case. Please provide a full log of the ion request using setLogging(Log.VERBOSE) and I can investigate further.

**Comment by sagarda7** [comment]
Hi koush,

This is the log while addHeader() was not working

	07-03 09:36:19.206  21076-21076/np.com.sagardevkota.gharbhada D/rentalHttp﹕ executiing
	07-03 09:36:19.206  21076-21076/np.com.sagardevkota.gharbhada D/rentalHttp﹕ (0 ms) http://sagardevkota.com.np/rental/api/v1/rentals: preparing request
	07-03 09:36:19.206  21076-21076/np.com.sagardevkota.gharbhada D/rentalHttp﹕ (0 ms) http://sagardevkota.com.np/rental/api/v1/rentals: preparing request
	07-03 09:36:19.211  21076-21076/np.com.sagardevkota.gharbhada I/rentalHttp﹕ (0 ms) http://sagardevkota.com.np/rental/api/v1/rentals: Using loader: com.koushikdutta.ion.loader.HttpLoader@42e29308
	07-03 09:36:19.211  21076-22132/np.com.sagardevkota.gharbhada D/rentalHttp﹕ (0 ms) http://sagardevkota.com.np/rental/api/v1/rentals: Executing request.
	07-03 09:36:19.211  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (3 ms) http://sagardevkota.com.np/rental/api/v1/rentals: Resolving domain and connecting to all available addresses
	07-03 09:36:19.216  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (5 ms) http://sagardevkota.com.np/rental/api/v1/rentals: attempting connection to sagardevkota.com.np/174.122.37.98:80
	07-03 09:36:23.166  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (3958 ms) http://sagardevkota.com.np/rental/api/v1/rentals: socket connected
	07-03 09:36:23.171  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (3962 ms) http://sagardevkota.com.np/rental/api/v1/rentals:
		POST /rental/api/v1/rentals HTTP/1.1
		Host: sagardevkota.com.np
		User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.3; SC-03E Build/JSS15J)
		Accept-Encoding: gzip, deflate
		Connection: keep-alive
		Accept: */*
		Apikey: **********************************************(not real)
	07-03 09:36:23.171  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (3964 ms) http://sagardevkota.com.np/rental/api/v1/rentals: request completed
	07-03 09:36:30.476  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (11265 ms) http://sagardevkota.com.np/rental/api/v1/rentals: Received headers:
		HTTP/1.1 301 Moved Permanently
		Date: Fri, 03 Jul 2015 03:51:32 GMT
		Server: Apache
		X-Pingback: http://www.sagardevkota.com.np/xmlrpc.php
		Expires: Wed, 11 Jan 1984 05:00:00 GMT
		Cache-Control: no-cache, must-revalidate, max-age=0
		Pragma: no-cache
		Location: http://www.sagardevkota.com.np/rental/api/v1/rentals
		Content-Length: 0
		Keep-Alive: timeout=5, max=100
		Connection: Keep-Alive
		Content-Type: text/html; charset=UTF-8
	07-03 09:36:30.481  21076-22132/np.com.sagardevkota.gharbhada D/rentalHttp﹕ (11270 ms) http://sagardevkota.com.np/rental/api/v1/rentals: Response is not cacheable
	07-03 09:36:30.481  21076-22132/np.com.sagardevkota.gharbhada I/rentalHttp﹕ (11272 ms) http://sagardevkota.com.np/rental/api/v1/rentals: Redirecting
	07-03 09:36:30.481  21076-22132/np.com.sagardevkota.gharbhada I/rentalHttp﹕ (11272 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: Redirected
	07-03 09:36:30.481  21076-22132/np.com.sagardevkota.gharbhada D/rentalHttp﹕ (0 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: Executing request.
	07-03 09:36:30.491  21076-22132/np.com.sagardevkota.gharbhada I/rentalHttp﹕ (9 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: Response may be served from conditional cache
	07-03 09:36:30.491  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (10 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: Resolving domain and connecting to all available addresses
	07-03 09:36:30.491  21076-22132/np.com.sagardevkota.gharbhada D/rentalHttp﹕ (11282 ms) http://sagardevkota.com.np/rental/api/v1/rentals: Recycling keep-alive socket
	07-03 09:36:30.496  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (13 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: attempting connection to www.sagardevkota.com.np/174.122.37.98:80
	07-03 09:36:30.981  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (498 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: socket connected
	07-03 09:36:30.981  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (499 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals:
		GET /rental/api/v1/rentals HTTP/1.1
		Host: www.sagardevkota.com.np
		User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.3; SC-03E Build/JSS15J)
		Accept-Encoding: gzip, deflate
		Connection: keep-alive
		Accept: */*
	07-03 09:36:30.981  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (501 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: request completed
	07-03 09:36:33.156  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (2676 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: Received headers:
		HTTP/1.1 200 OK
		Date: Fri, 03 Jul 2015 03:51:35 GMT
		Server: Apache
		Access-Control-Allow-Orgin: *
		Access-Control-Allow-Methods: *
		Cache-Control: max-age=0
		Expires: Fri, 03 Jul 2015 03:51:35 GMT
		Keep-Alive: timeout=5, max=100
		Connection: Keep-Alive
		Transfer-Encoding: chunked
		Content-Type: application/json
	07-03 09:36:33.176  21076-22132/np.com.sagardevkota.gharbhada D/rentalHttp﹕ (2695 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: Caching response
	07-03 09:36:33.181  21076-22132/np.com.sagardevkota.gharbhada V/rentalHttp﹕ (2698 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: Final (post cache response) headers:
		HTTP/1.1 200 OK
		Date: Fri, 03 Jul 2015 03:51:35 GMT
		Server: Apache
		Access-Control-Allow-Orgin: *
		Access-Control-Allow-Methods: *
		Cache-Control: max-age=0
		Expires: Fri, 03 Jul 2015 03:51:35 GMT
		Keep-Alive: timeout=5, max=100
		Connection: Keep-Alive
		Transfer-Encoding: chunked
		Content-Type: application/json
	07-03 09:36:33.181  21076-22132/np.com.sagardevkota.gharbhada D/rentalHttp﹕ (2700 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: Connection successful
	07-03 09:36:33.186  21076-21076/np.com.sagardevkota.gharbhada D/rentalHttp﹕ {"error":"No API Key provided"}
	07-03 09:36:33.191  21076-22132/np.com.sagardevkota.gharbhada D/rentalHttp﹕ (2709 ms) http://www.sagardevkota.com.np/rental/api/v1/rentals: Recycling keep-alive socket

in php part:

	<?php
		$headers=getallheaders();
		var_dump($headers);
	?>

but Apikey header is not received...

**Comment by koush** [comment]
Oh, you're losing headers on redirect.

**Comment by sagarda7** [comment]
How to preserve headers? can you give me idea?

**Comment by koush** [comment]
I'll need to fix this. Or go to the redirected URL in your ion call (www. prefix)

**Comment by zambral** [comment]
What about the fix?

Is there any updates?
