### ISSUE TITLE
Gradle build fails 

### ISSUE THREAD

**Issue by dante8300** [koush/ion#565]
Hi it really looks awesome what you have done i would like to give ti a try but i have not been able to make a gradle clean  or build  because it keeps throwing errors is there some specfic version of gradle needed to run this example? 

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\AndroidDev\ion\ion-sample\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating root project 'ion-sample'.
> Plugin with id 'com.android.application' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.153 secs

------------------------------------------------------------
Gradle 2.3
------------------------------------------------------------

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_25 (Oracle Corporation 23.25-b01)
OS:           Windows 8 6.2 amd64

**Comment by dandalf** [comment]
I haven't tried to build the sample, but I did get the library to build correctly by changing the build.gradle (https://github.com/dandalf/ion/blob/master/ion/build.gradle).  I think you could do something similar with the sample.

**Comment by koush** [comment]
apply plugin: 'com.android.library'

https://github.com/koush/ion/blob/master/ion/build.gradle

**Comment by dante8300** [comment]
Excuse me an old version of what? i have the latest Gradle installed and i just made again another git clone of the current branch.
