### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by RandomAltThing** [koush/ion#571]
@kouch

How do we download this? Also, is there a way I can get a .jar download because Eclipse is not working for me so I had to use AIDE, which doesn't support 1 click library installing.

**Comment by ppamorim** [comment]
This library was designed to be used on the Android Studio. But you can use .Jar too.

**Comment by RandomAltThing** [comment]
When I click Jar download it takes me back to the repo.

**Comment by ppamorim** [comment]
https://search.maven.org/remote_content?g=com.koushikdutta.ion&a=ion&v=LATEST

**Comment by RandomAltThing** [comment]
Thanks. Closing issue
