### ISSUE TITLE
RequestBuilder.addHeaders(Map<String, List<String>> headers)

### ISSUE THREAD

**Issue by lt-tibs1984** [koush/ion#577]
What is the purpose here for this setHeaders? setHeaders(NameValuePair.. pair) is not useful and old style.. NameValuePair is deprecated. If i have header "x", "x-value" and "y", "y-value" the addHeaders call doesn't make sense to use a Map<String, List<String>> it would make more sense to have a Map<String, String> for my headers. Can you please show how this is expected to be used in this context since there is no example I am seeing...

**Comment by koush** [comment]
setHeaders will replace any existing headers. addheaders will add headers to the list.

Ie,
Foo: bar
Foo: poo

are valid headers using addHeaders. Same header, with multiple values.

**Comment by koush** [comment]
NameValuePair is deprecated?

**Comment by coolya** [comment]
Yes since API level 22 it is.

**Comment by koush** [comment]
damnit i'm old

**Comment by lt-tibs1984** [comment]
Thanks, yeah i am now just calling addHeader(String header, String value)
multiple times. And this is working after i dove deeper into the
implementation i realize these are being added to a map
