### ISSUE TITLE
Image flashing in recyclerview

### ISSUE THREAD

**Issue by Anon28476** [koush/ion#587]
I have a custom adapter which loads image urls. These urls and than loaded using Ion. I poll the server for additional image urls to add to the recyclerview when the user reaches the end of the list or at periodic intervals both of which refresh the entire list.

The problem I have is the imageview flashes/blinks when calling notifyDataSetChanged. I have been able to partially sidestep this by using crossfade(true), but this has two problems. It still flashes once which I assume is the recyclerview rebinding the view and when a user scrolls down the list it will crossfade a previously bound image instead of fading in from a blank image.

**Comment by Anon28476** [comment]
So to anyone else who has this problem. I finally figured it out. Set crossfade to true in your Ion call and in onViewRecycled set your ImageView to null.

**Comment by asker517** [comment]
@Anon28476 can you show your code here? I have same issue. thanks

**Comment by jbemobile** [comment]
Try to not notify the changes of all the recicle and notify just the ones that changes or the ones that are you adding.

**Comment by asker517** [comment]
@jbemobile can you show your detail codes here? thanks
