### ISSUE TITLE
How to create a put request?

### ISSUE THREAD

**Issue by yy1300326388** [koush/ion#588]
How to create a put request?Thanks

**Comment by stratbasher** [comment]
https://github.com/koush/ion/issues?utf8=%E2%9C%93&q=is%3Aissue+put

When calling your load() function, use load("METHOD", uri).

Example:

    String response = Ion
             .with(getActivity().getApplicationContext())
             .load("PUT", "https://www.google.com")
             .asString()
             .get();

**Comment by yy1300326388** [comment]
thanks for you.
