### ISSUE TITLE
Cookie expire remove?

### ISSUE THREAD

**Issue by andrewpros** [koush/ion#601]
Does ION maintain cookie expires?

Will the previously obtained cookie be removed if the server send, a new, the same one but with expires in past?

This is a know, crucial technique to remove session cookies when logging out in php and i need this to work, the app will use this cookie to auth any request, so when i log out and destroy the session the cookie will be also send but with negative expire to remove it.

**Comment by andrewpros** [comment]
Anyone?

**Comment by koush** [comment]
Yes, its managed by CookieManager/CookieStore. Check the implementation!

https://github.com/koush/ion/blob/master/ion/src/com/koushikdutta/ion/cookie/CookieMiddleware.java

**Comment by andrewpros** [comment]
@koush Thx, looks like it works.
