### ISSUE TITLE
Force ion to load from cache

### ISSUE THREAD

**Issue by shilch** [koush/ion#606]
How can I tell ion to load url from cache (if it's in cache)?
something like this:
```java
Ion.with(mContext)
    .load("GET","http://127.0.0.1/example.json")
    .fromCache()
    .asJsonObject()
    .setCallback(new FutureCallback<JsonObject>() {
        @Override
        public void onCompleted(Exception e, JsonObject result) {
            if (e != null){
                e.printStackTrace();
                ...
                return;
            }
            if (result == null){
                // nothing stored in cache
            }
            else {
                doSomething();
            }
        }
    });
```

Hope you understand what I mean.
Thank you very much in advance.

**Comment by Saren-Arterius** [comment]
I guess there is already asCachedBitmap() method in BitmapFutureBuilder

**Comment by shilch** [comment]
I already saw that, but it would be useful if loading JSONs from the cache. But I've already solved my problem by writing my own caching class and disabling ion-caching. Nevertheless many thanks
