### ISSUE TITLE
How can I custom Gson in Ion?

### ISSUE THREAD

**Issue by yaohsieh** [koush/ion#620]
a POJO like this:
<img width="352" alt="5995753d-c37f-48e8-a116-175cd37f0677" src="https://cloud.githubusercontent.com/assets/12838329/9725626/cdde6ca4-5619-11e5-858f-c0d0938fc6ca.png">

I did this with Ion:
<img width="402" alt="1c10731a-4121-4177-b662-9b4545e2556b" src="https://cloud.githubusercontent.com/assets/12838329/9725619/aea99e76-5619-11e5-90f4-1573c175408e.png">

But it failed to convert json to pojo, throws StackOverflowError because of circular reference in the object.

And Realm suggest to use this solution:

<img width="584" alt="fcd8eec6-177d-4fa6-99ec-2c6e33db80f8" src="https://cloud.githubusercontent.com/assets/12838329/9725596/693a5b14-5619-11e5-98df-0e865b166776.png">

This solution works fine, but it's inconvenient.

Is there any way to custom Gson and I can use as(SomPOJO.class) again?

**Comment by koush** [comment]
You can access and customize Ion's Gson object Ion.getDefault.getGson

**Comment by yaohsieh** [comment]
I customized Gson globally like this:
Ion.getDefault(this).configure().setGson()
