### ISSUE TITLE
Make http response cache size configurable

### ISSUE THREAD

**Issue by rayworks** [koush/ion#621]
Hi there,

Compared with other libraries, I found Ion has better performance for listview. However,
It has a default file cache size(10MB) for http response which will remove image files automatically for my usage. 

https://github.com/koush/ion/blob/master/ion/src/com/koushikdutta/ion/Ion.java#L162

I was wondering if it might be possible to provide an option for making basic settings configurable instead of hardcoded values ?

**Comment by koush** [comment]
You can reconfigure it after it has been set up. Nothing is purged until something is attempted to be written.

**Comment by koush** [comment]
use getResponseCache I think.

**Comment by rayworks** [comment]
Thank you!  It works.

```
FileCache fileCache = Ion.getDefault(context).configure().getResponseCache().getFileCache();
fileCache.setMaxSize(IMAGE_CACHE_SIZE);
```

**Comment by Nilzor** [comment]
Semi-relevant question: How is in-memory cache sized? Is it configurable? Should I worry about memory consumption when caching is enabled?

**Comment by rayworks** [comment]
@Nilzor You can check class `IonBitmapCache`.  And I don't think you need to care about memory cache size.
