### ISSUE TITLE
Clear cache for a single URL

### ISSUE THREAD

**Issue by andytriboletti** [koush/ion#677]
I'm working on an iOS and Android app. In iOS I use SDWebImage and there's a method to clear the cache for a single URL. Does such a method exist in ion?  I actually am using URLImageViewHelper, but when I went to look for docs I saw I should use ion now.

The method in SDWebImage:
    [[SDImageCache sharedImageCache] removeImageForKey:imageURL fromDisk:YES];

**Comment by andytriboletti** [comment]
I ended up switching to Picasso. http://square.github.io/picasso/

**Comment by norman-kapschefsky** [comment]
Hi @andytriboletti ,
you may can use the following to delete a single file from the external file cache:

``` 
Ion ion = Ion.getDefault(CONTEXT);

// get bitmap info where key is stored
BitmapInfo bitmapInfo = ion.load(IMAGE_URL).asCachedBitmap();

if (bitmapInfo != null) {
     // this key should be the file name
     String key = bitmapInfo.key;

     // try to find the file for that key in the cache directory

     // here all cached files from ion are listed 
     File[] files = new File(APP_CONTEXT.getCacheDir(), ion.getName()).listFiles();

     // iterate through list or get the file directly via "new File(path to file) and call "delete()" on it
}
``` 

I'v tested Picasso as well a few days ago but I got a lot of network exceptions in production environment. Ion has crashes as well but not that much.

**Comment by koush** [comment]
46f5c11

**Comment by koush** [comment]
2260a31
