### ISSUE TITLE
Can't pinch to zoom ImageView with deepZoom

### ISSUE THREAD

**Issue by VedavyasBhatNomadly** [koush/ion#699]
I have an `ImageView` in a `PopupWindow`:

    LinearLayout popupView = (LinearLayout) layoutInflater.inflate(R.layout.image_popup, null);
    ImageView imagePopup = (ImageView) popupView.findViewById(R.id.imagePopup);

    Ion.with(getApplicationContext())
        .load(imageFileUrl)
        .withBitmap()
        .deepZoom()
        .intoImageView(imagePopup);

    imagePopupWindow = new PopupWindow(
        popupView,
        LinearLayout.LayoutParams.MATCH_PARENT,
        LinearLayout.LayoutParams.MATCH_PARENT
    );
    imagePopupWindow.setBackgroundDrawable(new ColorDrawable());
    imagePopupWindow.setOutsideTouchable(false);
    imagePopupWindow.showAtLocation(findViewById(R.id.listView), Gravity.CENTER, 0, 0);

`image_popup` file:

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    <ImageView
        android:id="@+id/imagePopup"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerCrop"
        android:background="@color/black"/>
    </LinearLayout>

but I can't pinch to zoom on it. Any idea why, or how I can debug this further?

**Comment by jonasbark** [comment]
although this is an old ticket...
deepZoom won't enable pinch to zoom on the ImageView. Look at the video description:
https://www.youtube.com/watch?v=yIMltNEAKZY
You have to use e.g. the PhotoView library.

**Comment by VedavyasBhatNomadly** [comment]
I thought that was for demonstration purposes only.
I'm using it with PhotoView now and it works perfectly.
@koush Does it work only with PhotoView? If so, shouldn't PhotoView be a dependency of Ion?

**Comment by koush** [comment]
no, it shouldnt be a dependency. iondrawable manages the drawable render calls to scale and load the image appropriately. will work with anything that takes a drawable as an input.
