### ISSUE TITLE
Thumbnails and Images not loading often

### ISSUE THREAD

**Issue by kanaksony** [koush/ion#700]
Greetings,

We are running your sample and found that it often fails to load thumbnails and images. Images we are trying to open are local only.

### Issue 1 : In Portrait Mode (same applies for Landscape mode): 

Column 8 : thumbnails size [1200/8 = 150 approx (padding / margins not calculated)]
It renders thumbnails fine without error drawable every time (tested almost 10 times).

Column 5 :  thumbnails size [1920/8 = 240 approx (padding / margins not calculated)]
It renders few thumbnails with error drawable every time (tested almost 10 times).

Attaching screenshot for same.

![corrupt_device-2016-03-02-161750](https://cloud.githubusercontent.com/assets/6097596/13458758/3aa58ede-e095-11e5-984d-5e46f4009227.png)

![nocorrupt_device-2016-03-02-161912](https://cloud.githubusercontent.com/assets/6097596/13458759/3d6a190a-e095-11e5-9770-86a38f60000f.png)

The stack trace is having no message but we captured via debug :
```
e = {com.koushikdutta.ion.bitmap.BitmapDecodeException@4164} "com.koushikdutta.ion.bitmap.BitmapDecodeException size=-1x-1"
 height = -1
 width = -1
 cause = {com.koushikdutta.ion.bitmap.BitmapDecodeException@4164} "com.koushikdutta.ion.bitmap.BitmapDecodeException size=-1x-1"
 detailMessage = null
 stackState = {int[12]@4170} 
 stackTrace = {java.lang.StackTraceElement[0]@4171} 
 suppressedExceptions = {java.util.Collections$EmptyList@4172}  size = 0
 shadow$_klass_ = {java.lang.Class@70} "class com.koushikdutta.ion.bitmap.BitmapDecodeException"
 shadow$_monitor_ = -1929624325

```
### Issue 2 :
It does not open some images at all and fails with Exception in logs. 
`java.io.IOException: Image failed to decode using BMP decoder`

Can you please help in understanding the issue?

**Comment by koush** [comment]
the image is corrupted probably.
