### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by roryrudy** [koush/ion#702]
I need to know when Ion Timeout. That way I can send a message to the user and not having the user waiting. I have been searching and cannot find anything. Any help would be appreciated.

**Comment by WasimMemon** [comment]
You can do like this 

```
.setCallback(new FutureCallback<JsonObject>() {
    @Override
    public void onCompleted(Exception e, JsonObject result) {
        if (pd.isShowing()) {
            pd.cancel();
        }

        if (e != null) {

            if (e instanceof TimeoutException)
            {
                Utility.showToast(ctx,
                        AppConfig.getContext().getResources().getString(R.string.msg_Connection_error)
                );

                CancelAllRequest(AppConfig.getContext());

                return;
            }
        }
    }
});
```

**Comment by mohitkumar0571** [comment]
@roryrudy This may be helpful as you can set time out through OkhttpClient in each request
[Android Networking Complete networking](https://github.com/amitshekhariitbhu/AndroidNetworking)
