### ISSUE TITLE
Pass ArrayList<String> parameter in request body ?

### ISSUE THREAD

**Issue by ktiniatros** [koush/ion#705]
Hi,

the backend I'm dealing with (and unfortunately I have no control on) has the following requirements:

/v1/availabilities POST
retrieve availabilities for a company service id and selected employees

body
service::string - The company service id
employees::Array - An array of strings with the selected employee ids per sub service (should be passed even if it is an empty array)

How can I pass an array of strings in the body parameters?

`ArrayList<String> employees = new ArrayList<>();`
`JsonObject params = new JsonObject();`
`params.addProperty("service", "serviceId");`
`params.addProperty("employees", ???);`
`Ion.with(this).load(url).setJsonObjectBody(params)`

**Comment by jlhonora** [comment]
You'll have to pass a JsonArray:

```
List<String> strings = new ArrayList<>();
JsonArray stringsJson = new JsonArray();
for (String str : strings) {
	stringsJson.add(str);
}
jsonBody.add("strings", stringsJson);
```

**Comment by ktiniatros** [comment]
You cannot add a `String` to a `JsonArray `

**Comment by ktiniatros** [comment]
Aw, you can actually do ` stringsJson.add(new JsonPrimitive(str))`

I'll try this.
