### ISSUE TITLE
how scale images before caching and cache scaled images not original size 

### ISSUE THREAD

**Issue by se8820726** [koush/ion#706]
hi
I am using ion library in my app for getting images from server and show them in imageviews.
now I have 2 question.
1- how scale images before caching and cache scaled images not original size ?
there is a method named resize() in ion. does this method cache resized image on original image after resizing or not ?
2- where does save chached images in app? is in app ram or in phone internal memory?

**Comment by koush** [comment]
1- use a transform.
2- in the app data directory
