### ISSUE TITLE
setHeader() silently crashes call when string value is too long

### ISSUE THREAD

**Issue by dinamicrod** [koush/ion#714]
I was attempting to send a very long JWT in the Authorization header.
setHeader( "Authorization", "Bearer: <jwt_value>" )

The library will not pop any error and won't crash the app. However, the call was not made either.
After several tests, I realised the JWT value was too long. Setting it to less then 750 characters (might need further tests to get accurate supported max length) did the trick.

Regards, 

rod-

**Comment by mohitkumar0571** [comment]
@dinamicrod  This may be helpful
[Android Networking Complete networking](https://github.com/amitshekhariitbhu/AndroidNetworking)

**Comment by rlinyard** [comment]
Unfortunately, it is difficult for me to control the length of the bearer token, so some of my web API calls fail. That token works for some calls, but I'm having trouble with a JSON PUT call with this long token. What is the limit?

**Comment by koush** [comment]
This passes for me:
```java
    public void testIssue714() throws Exception {
        AsyncHttpServer server = new AsyncHttpServer();
        server.get("/test", new HttpServerRequestCallback() {
            @Override
            public void onRequest(AsyncHttpServerRequest request, AsyncHttpServerResponse response) {
                response.send(request.getHeaders().get("Authorization"));
            }
        });
        int port = server.listen(Ion.getDefault(getContext()).getServer(), 0).getLocalPort();
        String auth = "";
        for (int i = 0; i < 1024; i++) {
            auth += (char)('0' + (i % 10));
        }
        System.out.println(auth);
        assertEquals(auth, Ion.with(getContext())
        .load("http://localhost:" + port + "/test")
        .setHeader("Authorization", auth)
        .asString()
        .get());
    }
```

It may be your server end that is crashing? Are you also sending a POST body, or just a GET request?

**Comment by rlinyard** [comment]
It is a PUT request. The request works from Postman, so I know it is not a server issue.

Here is the “raw” header:

Host:192.168.2.20:14675
User-Agent:Dalvik/2.1.0 (Linux; U; Android 6.0.1; SAMSUNG-SM-G920A Build/MMB29K)
Accept-Encoding:gzip, deflate
Connection:keep-alive
Accept:*/*
Accept:application/json
content-type:application/json
authorization:Bearer cMqyjudPWkPD7B9FBXGCJZyLu8Uoo4r191f1lDL3GhUbcRYpgLp-r99a7ODe77Aal4Rs8wWGY8kKNaCp7HLbqN0UGFb7Z9ZnokJuTWfZMkw8vEU7FE6h1iHSQ-y8WdsHCoBddkCFi8pXkj42g2GxZrmrOmDp-woejPHLgmbahs8_pQL2BgkWeJUeZlS-Q5iaDoBxiNL3jxKtYSClUcmO1uWscceKM1AXaJvrwIUg0FJM0X9aWUyYWEPDhgoYUggaOBNOciMJnAef8-SbuLWNvDVLLJjSN2KFc8VPhvCbo0suhGJrakZXTfNDhhVryuSr4rn5KMYH8udiAlCrG9RBMcYhY8xrLosOn67ETmBPjUYOCFd6i_fTqXKj5DKLk2Di26yVOd2Ilao_TqoNIBQg88kTgfoq2itWBX4s49kEl7aZvxUU0cRuNR3iSLhOL7aQ_8jrCKEL9IDV0okVYdjczuRF20yjwcU57Ffsd8O0cfYuaIM7UCU09f609j-84zUffa7fGGkgy6XrUE88emzxzovjqXZClCKCKCp6KQMn52SiNpJyLryVWzVTxjyQjxzJ7qigMpzJZBFRuZGOksEBDWyGgcYNwom63NsT7YvfevyrvsTqETYZTVvc3BCkcJZDb1FCe9Vwu16DjkrW2WWCipp3wKCQuPIzLI0W0XPSL-xm4qNrvkBUrFjFOzGq0HuL92RLrFGdd0-FoSdOphR—b1mM2U

Here is the body:

{ ShouldDisplayInDirectory: true, ShouldReceivePushNotifications: true, ShouldReceiveEmailNotifications: true, CategoryIds: [174, 175, 176]}




On Aug 13, 2016, at 3:22 PM, Koushik Dutta <notifications@github.com<mailto:notifications@github.com>> wrote:


This passes for me:

    public void testIssue714() throws Exception {
        AsyncHttpServer server = new AsyncHttpServer();
        server.get("/test", new HttpServerRequestCallback() {
            @Override
            public void onRequest(AsyncHttpServerRequest request, AsyncHttpServerResponse response) {
                response.send(request.getHeaders().get("Authorization"));
            }
        });
        int port = server.listen(Ion.getDefault(getContext()).getServer(), 0).getLocalPort();
        String auth = "";
        for (int i = 0; i < 1024; i++) {
            auth += (char)('0' + (i % 10));
        }
        System.out.println(auth);
        assertEquals(auth, Ion.with(getContext())
        .load("http://localhost:" + port + "/test")
        .setHeader("Authorization", auth)
        .asString()
        .get());
    }

It may be your server end that is crashing? Are you also sending a POST body, or just a GET request?

**Comment by rlinyard** [comment]
I should have noted a couple of other things:

1. Thank you very much for responding!
2. I was using Charles to monitor all calls, and this call is never being made (it is never seen in Charles). Again - it dies somewhere in the request chain and not as a result of a server error.

Thanks again,

Ron

On Aug 13, 2016, at 3:25 PM, Ron Linyard <ron@1218team.com<mailto:ron@1218team.com>> wrote:

It is a PUT request. The request works from Postman, so I know it is not a server issue.

Here is the “raw” header:

Host:192.168.2.20:14675
User-Agent:Dalvik/2.1.0 (Linux; U; Android 6.0.1; SAMSUNG-SM-G920A Build/MMB29K)
Accept-Encoding:gzip, deflate
Connection:keep-alive
Accept:*/*
Accept:application/json
content-type:application/json
authorization:Bearer cMqyjudPWkPD7B9FBXGCJZyLu8Uoo4r191f1lDL3GhUbcRYpgLp-r99a7ODe77Aal4Rs8wWGY8kKNaCp7HLbqN0UGFb7Z9ZnokJuTWfZMkw8vEU7FE6h1iHSQ-y8WdsHCoBddkCFi8pXkj42g2GxZrmrOmDp-woejPHLgmbahs8_pQL2BgkWeJUeZlS-Q5iaDoBxiNL3jxKtYSClUcmO1uWscceKM1AXaJvrwIUg0FJM0X9aWUyYWEPDhgoYUggaOBNOciMJnAef8-SbuLWNvDVLLJjSN2KFc8VPhvCbo0suhGJrakZXTfNDhhVryuSr4rn5KMYH8udiAlCrG9RBMcYhY8xrLosOn67ETmBPjUYOCFd6i_fTqXKj5DKLk2Di26yVOd2Ilao_TqoNIBQg88kTgfoq2itWBX4s49kEl7aZvxUU0cRuNR3iSLhOL7aQ_8jrCKEL9IDV0okVYdjczuRF20yjwcU57Ffsd8O0cfYuaIM7UCU09f609j-84zUffa7fGGkgy6XrUE88emzxzovjqXZClCKCKCp6KQMn52SiNpJyLryVWzVTxjyQjxzJ7qigMpzJZBFRuZGOksEBDWyGgcYNwom63NsT7YvfevyrvsTqETYZTVvc3BCkcJZDb1FCe9Vwu16DjkrW2WWCipp3wKCQuPIzLI0W0XPSL-xm4qNrvkBUrFjFOzGq0HuL92RLrFGdd0-FoSdOphR—b1mM2U

Here is the body:

{ ShouldDisplayInDirectory: true, ShouldReceivePushNotifications: true, ShouldReceiveEmailNotifications: true, CategoryIds: [174, 175, 176]}




On Aug 13, 2016, at 3:22 PM, Koushik Dutta <notifications@github.com<mailto:notifications@github.com>> wrote:


This passes for me:

    public void testIssue714() throws Exception {
        AsyncHttpServer server = new AsyncHttpServer();
        server.get("/test", new HttpServerRequestCallback() {
            @Override
            public void onRequest(AsyncHttpServerRequest request, AsyncHttpServerResponse response) {
                response.send(request.getHeaders().get("Authorization"));
            }
        });
        int port = server.listen(Ion.getDefault(getContext()).getServer(), 0).getLocalPort();
        String auth = "";
        for (int i = 0; i < 1024; i++) {
            auth += (char)('0' + (i % 10));
        }
        System.out.println(auth);
        assertEquals(auth, Ion.with(getContext())
        .load("http://localhost:<http://localhost/>" + port + "/test")
        .setHeader("Authorization", auth)
        .asString()
        .get());
    }

It may be your server end that is crashing? Are you also sending a POST body, or just a GET request?

**Comment by koush** [comment]
ok i've reproduced it, fixing.

**Comment by koush** [comment]
6c450d1
