### ISSUE TITLE
problem with 2.1.7

### ISSUE THREAD

**Issue by muhammad-naderi** [koush/ion#716]
Hi,

I always use the 
``compile 'com.koushikdutta.ion:ion:2.+'
`line in my gradle, but as lint always warns us ... this is a "BAD" thing to do, even when the author says to use it.

any way I was working ok with the 2.1.6 release, until yesterday that I let the gradle go online, since then one of my calls got stuck after executing request and never heard the answer. 

I tried everything, checked the endpoint with postman, changed the parameters,, everything !

then I just remembered that maybe letting gradle to go online caused the problem so I checked and found out I have two versions of `ion` in the gradle files, 2.1.6  and 2.1.7 so I changed the compile line from 2.+ to 2.1.6 and everything is working fine again.

this is the piece of code which creates the call :

```
result = Ion.with(mContext)
                    .load(url)
                    .setLogging("WSLOG",android.util.Log.DEBUG)
                    .addHeader("CustomerNo", TActivation.getCustomerNumber())
                    .setJsonArrayBody((xJsonArray != null)?new Gson().fromJson(xJsonArray.toString(), JsonArray.class):new JsonArray())
                    .asJsonObject()
                    .get();
```

and if you needed more help about it, the xJsonArray in the test case would be null, and the TActivation.getCustomerNumber() is a five char length long string, also url is ok, as I told you it works fine in postman and 2.1.6
if you need more info, let me know

**Comment by x4vl** [comment]
Same issue here!

**Comment by mohitkumar0571** [comment]
@muhammad-naderi This may be helpful
[Android Networking Complete networking](https://github.com/amitshekhariitbhu/AndroidNetworking)

**Comment by koush** [comment]
can you test http vs https?

**Comment by muhammad-naderi** [comment]
the url which I use is http, and unfortunately our endpoints does not support https.
but if you need, you can give me some endpoints and I will check them out and let you know

**Comment by kfwong** [comment]
Hi koush, I've tested POST method on my self-signed cert with https, same issue with the logging stuck at executing request. Version 2.1.6 temporarily fixed the issue. fyi, the GET method are working fine on https.

GET and POST methods on simple http, both are working fine.

**Comment by muhammad-naderi** [comment]
apparently the issue is resolved in 2.1.8

**Comment by seeaui** [comment]
issue

**Comment by muhammad-naderi** [comment]
spending some time, I found that the problem is with header's length, same as this issue 
https://github.com/koush/ion/issues/718

and the problem is not with endpoint at least, since sending exact same request with postman works well

**Comment by koush** [comment]
fixed https://github.com/koush/AndroidAsync/commit/be28a1583e2bd4b9c3f2a1ecb292ceaf1088b934
