### ISSUE TITLE
onCompleted is not being called after the api is done.

### ISSUE THREAD

**Issue by mohamed-habib** [koush/ion#717]
Hi, i am using ion to upload files to my server, is used this code :
```
            Ion.with(context)
                    .load("POST", "URL")
                    .setMultipartFile("file", FileUtils.getFile(context, AttachmentUri())))
                    .asJsonObject()
                    .setCallback(new FutureCallback<JsonObject>() {
                        @Override
                        public void onCompleted(Exception e, JsonObject result) {
                            Log.d("Upload", "result: " + result.toString());
                            Log.d("Upload", "Ex: " + e.toString());
                        }
                    });
```
the file was uploaded correctly but the code inside onComplete method wasn't called.

can any one see any problem in my code ?

**Comment by asker517** [comment]
Maybe you should check your context lifecycle first

Mohamed Habib <notifications@github.com>于2016年5月6日 周五20:12写道：

**Comment by mohamed-habib** [comment]
@asker517 can you explain more ?

**Comment by asker517** [comment]
For example if you context was died before you request is finish , you will
not receive the callback
Mohamed Habib <notifications@github.com>于2016年5月7日 周六20:25写道：

**Comment by mohamed-habib** [comment]
I'm not very sure if the context died or not, but it'd be better if i used getApplicationContext() to make sure that the context is alive as long as the app. is alive, right ?

**Comment by asker517** [comment]
@mohamed-habib is solved?

**Comment by mohamed-habib** [comment]
Yes, Thank you.
