### ISSUE TITLE
Resume http file download

### ISSUE THREAD

**Issue by nomade** [koush/ion#720]
Is possible continue file download with Ion?

In HttpConnection I use:
`
urlConnection.setRequestProperty ("Accept-Ranges", "bytes");
`
`
urlConnection.setRequestProperty ("Range," "byte = "+downloadResume) +" - ");
`

In ION I try:
`
Ion.with(context).load(url)...
`
`
        if(fileIsNotCompleted && fileSave.length()>0) {
`
`
            ion.setHeader("Accept-Ranges", "bytes");
`
`
            ion.setHeader("Range", "bytes=" + fileSave.length()+"-");
`
`
        }
`
`
        ion.write(fileSave).setCallback(new FutureCallback<File>() {
`
`
           public void onCompleted(Exception e, File file) {
`
`
                fileIsNotCompleted = true;
`
`
          }
`
`
       }).get();
`
`
       return fileIsNotCompleted;
`
`

**Comment by nomade** [comment]
Work with:

` 
ion.write(fos).setCallback(new FutureCallback<FileOutputStream>() {
` 
` 
            @Override
` 
` 
            public void onCompleted(Exception e, FileOutputStream fileOutputStream) {
` 
` 
                if (e != null) {
` 
` 
                    e.printStackTrace();
` 
` 
                    return;
` 
` 
                }
` 
` 
                    fileOutputStream.flush();
` 
` 
                    fileOutputStream.close();
` 
` 
            }
` 
` 
        }).get();`
` 
`

**Comment by mkaarthick** [comment]
@nomade is it working? :100:
