### ISSUE TITLE
Write images to external storage as well

### ISSUE THREAD

**Issue by zubinmehta** [koush/ion#721]
Hi,

I see that ion doesn't support writing to external storage and with good reason!

But is there any way, I can create a copy of images to the external storage once it gets downloaded ?

I am fine with it being stored in LRU cache as well. 

Thanks.

**Comment by amitshekhariitbhu** [comment]
You can use this library . This library supports this
[Android Networking](https://github.com/amitshekhariitbhu/AndroidNetworking)

**Comment by mohitkumar0571** [comment]
This may be helpful
[Android Networking Complete networking](https://github.com/amitshekhariitbhu/AndroidNetworking)
