### ISSUE TITLE
Properly manage non-2XX response codes

### ISSUE THREAD

**Issue by koush** [koush/ion#79]
.write(file), and other always-succeed methods should not succeed on non-2XX response codes.

**Comment by andrewjackman** [comment]
I also want to be able to do the same as @dmapr . I have a web service I connect to that returns JSON on 2xx, but also a JSON body containing error messages on 4xx. I've spent the day trying to figure out a way to achieve this using TransformFuture, however I think I misunderstood what it was for and couldn't get it to work.

**Comment by koush** [comment]
withResponse lets one custom manage response codes. leaving logic up to the caller.
