### ISSUE TITLE
Dynamic Images

### ISSUE THREAD

**Issue by scysys** [koush/ion#792]
Hello,

really great Project and saved me a lot of time. :)

Can you add possibility to change image dynamically?
URL Rotation is not the problem, but

`.load("http://example.com/image.jpg");`

is only changed when restarting the app.

**Comment by cyberjacob** [comment]
chain `.noCache()` after your `.load()` call, this will bypass the cache and always get the latest version of the image.

**Comment by djdance** [comment]
hmm, there is no .noCache not before, nore after .load
version 3.1.0
`Ion.with(im).load(logo);`
