### ISSUE TITLE
Application cashes when the connection is lost during the process

### ISSUE THREAD

**Issue by cristarra** [koush/ion#793]
When the process of requesting Json to server in progress, and an Internet connection dies. then the response is very long for waiting. until the application crashes. Exception e is null and no value result.getHeaders ().code().

I found the error as below:

E/AndroidRuntime: FATAL EXCEPTION: main
Process: radio.online.indonesia.tarrasmart, PID: 22910
java.lang.NullPointerException: Attempt to invoke virtual method 'com.koushikdutta.ion.HeadersResponse
com.koushikdutta.ion.Response.getHeaders()' on a null object reference                      
at radio.online.indonesia.tarrasmart.MainActivity$2.onCompleted(MainActivity.java:294)                     
at radio.online.indonesia.tarrasmart.MainActivity$2.onCompleted(MainActivity.java:290)
at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:141)
at com.koushikdutta.ion.IonRequestBuilder$EmitterTransform$1.onCompleted(IonRequestBuilder.java:459)
at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:141)
at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:124)
at com.koushikdutta.ion.IonRequestBuilder$1.run(IonRequestBuilder.java:244)
at com.koushikdutta.async.AsyncServer$RunnableWrapper.run(AsyncServer.java:60)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7231)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

If the Internet is stable then the code runs fine,  but when the process is already underway and the Internet is dead or run slowly. then the application crashes.

This is my program code snippet:

`        final ProgressDialog dialog = new ProgressDialog(this);
        dialog.setProgressStyle(ProgressDialog.STYLE_SPINNER);
        dialog.setMessage("Loading, please wait...");
        dialog.setIndeterminate(true);
        dialog.setCanceledOnTouchOutside(false);
        dialog.setCancelable(false);
        dialog.show();

        if(haveNetworkConnection()) {
                Ion.with(getApplicationContext())
                        .load(get_token_url())
                        .setBodyParameter("oauth-user", user_key())
                        .setBodyParameter("oauth-password", security_key())
                        .setBodyParameter("submit-oauth", "Get-Token")
                        .asString()
                        .withResponse()
                        .setCallback(new FutureCallback<Response<String>>() {
                            @Override
                            public void onCompleted(Exception e, Response<String> result) {
                                if (result.getHeaders().code() == 200 && e == null) {
                                    final String json = result.getResult();
                                    try {
                                        JSONObject obj = new JSONObject(json);
                                        if (obj.getString("Status").equals("Success")) {
                                            String token = obj.getString("Token");
                                            Ion.with(getApplicationContext())
                                                    .load(key_url()+"?request=radioserver&key=" + stream_key + "&token=" + token)
                                                    .asString()
                                                    .withResponse()
                                                    .setCallback(new FutureCallback<Response<String>>() {
                                                        @Override
                                                        public void onCompleted(Exception e, Response<String> result) {
                                                            if (result.getHeaders().code() == 200 && e == null) {
                                                                final String json = result.getResult();
                                                                try {
                                                                    JSONObject obj = new JSONObject(json);
                                                                    if (obj.getString("Status").equals("Success")) {
                                                                        Intent intent = new Intent(getApplicationContext(),
                                                                                service.class);
                                                                        intent.putExtra(service.START_PLAY, true);
                                                                        Bundle b = new Bundle();
                                                                        b.putString("titlePlayer", titlePlayer);
                                                                        b.putString("Streaming_url", obj.getString("IP"));
                                                                        intent.putExtras(b);
                                                                        startService(intent);
                                                                        dialog.dismiss();
                                                                    } else {
                                                                        if (dialog != null && dialog.isShowing()) {
                                                                            dialog.dismiss();
                                                                        }
                                                                    }
                                                                } catch (Throwable t) {
                                                                    if (dialog != null && dialog.isShowing()) {
                                                                        dialog.dismiss();
                                                                    }
                                                                }
                                                            } else {
                                                                if (dialog != null && dialog.isShowing()) {
                                                                    dialog.dismiss();
                                                                }
                                                            }
                                                        }
                                                    });
                                        } else {
                                            if (dialog != null && dialog.isShowing()) {
                                                dialog.dismiss();
                                            }
                                        }
                                    } catch (Throwable t) {
                                        if (dialog != null && dialog.isShowing()) {
                                            dialog.dismiss();
                                        }
                                    }
                                } else {
                                    if (dialog != null && dialog.isShowing()) {
                                        dialog.dismiss();
                                    }
                                }
                            }
                        });            
        }else{
            if (dialog != null && dialog.isShowing()) {
                dialog.dismiss();
                Toast.makeText(getApplicationContext(), "Opss!, No.. Connection", Toast.LENGTH_SHORT).show();
            }
        }`

How do I handle this problem?

**Comment by ludm** [comment]
Hello, I have the same kind of problem in Android Virtual Device, and I have checked in the Android Web Navigator, I have got this message net::ERR_NAME_NOT_RESOLVED. So it seems to happen when there is a DNS problem.

**Comment by SubhashBadri** [comment]
Hello,
 I am using the ion version 2.1.9 and I see still see this issue. Here is the repro step.
I login into my app
go to settings and remove the network connection.
relaunch the app.
-> Crash with the same issue mentioned here (null exception using getHeaders())

Any help is appreciated.
Thanks,
Subhash Badri
