### ISSUE TITLE
Tls 1.2 and Android 4.4

### ISSUE THREAD

**Issue by maxglu** [koush/ion#821]
Hi! Thanks for excellent library!
I have a litle question, how I can enable TLS 1.2 support with  ion?
In this time I got exception javax.net.ssl.SSLException: Fatal alert received handshake_failure on Android 4.4
But I do not receive this error on Android 5.1 device. I think problem with Android TLS support (TLS 1.2 supports only from api 20 and later)
PS Sorry for my English :)

**Comment by nigharsh** [comment]
@maxglu any updates on this?

**Comment by maxglu** [comment]
@nigharsh With ion unfortunately no. 
But I replaced ion with okHttp and solved my problem using [this workaround  ](https://github.com/square/okhttp/issues/2372#issuecomment-244807676)

**Comment by koush** [comment]
If you use google play services, it works. it will use the conscrypt ssl stack that ships with google play devices.

**Comment by nigharsh** [comment]
2.2.2 works. Verified on 4.4.4 and 4.2 with 10.2 and 11.0. Thanks.

**Comment by madrzazg** [comment]
Is there any way to enable TLS 1.2 without using google play services or conscrypt?
