### ISSUE TITLE
TLS using SNI fails when using conscrypt MW after recent Google Play Services update

### ISSUE THREAD

**Issue by henhal** [koush/ion#827]
Hi,

Yesterday a lot of our phones stopped being able to contact our backend. The backend runs on AWS with CloudFront at the front (AWS API gateway actually). Apparently CloudFront uses SNI. This seems to correlate to a recent update of Google Play Services being pushed out because it gradually affected more and more of our phones.

When contacting our EC2 servers directly, it works fine, but when going through CloudFront it fails. Before the Google Play Service update both worked fine for months.

After digging around I found a workaround - disabling conscrypt MW in Ion solves the issue.

But is this the proper way to solve this or should Ion add some missing support for SNI in combination with conscrypt? I do not really understand the consequences of disabling conscrypt, but some sources indicate it's not a good idea. 

@koush do you have any info on what the root cause is here and what the best solution might be to be able to use Ion together with TLS 1.2/SNI without any hacks or workarounds?

For reference I also put this Q&A on SO: https://stackoverflow.com/questions/44307801/android-app-using-ion-for-https-requests-fail-seemingly-after-google-play-servi

**Comment by henhal** [comment]
After updating to Ion 2.1.9 this seems resolved.

**Comment by ammojamo** [comment]
I think I am also experiencing this issue. Everything was working fine before GMS update, and disabling Conscrypt Middleware also make the problem go away.

In my case, the server is not behind CloudFront but is using SNI. (SSLLabs reports a good configuration and no other SNI compatible clients have any issues).

Relevant stack trace:
```
Peer not trusted by any of the system trust managers.
com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.
at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:322)
..snip..
Caused by: javax.net.ssl.SSLException: hostname <portal.birdlife.org.au> has been denied
at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:306)
..snip
```

**Comment by ammojamo** [comment]
Rolling back to version 2.1.7 of Ion also 'fixes' the problem

**Comment by JFBBSony** [comment]
Rolling back to 2.1.7 doesn't fix our problem unfortunately.
`E/Ion: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
                                                              javax.net.ssl.SSLHandshakeException: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
                                                                  at wqv.a(:com.google.android.gms:48)
                                                                  at wqv.a(:com.google.android.gms:27)
                                                                  at wqv.a(:com.google.android.gms:91)
                                                                  at wqv.a(:com.google.android.gms:106)
                                                                  at wqv.unwrap(:com.google.android.gms:3)
                                                                  at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
                                                                  at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                                  at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
                                                                  at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
                                                                  at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
                                                                  at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
                                                                  at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)`

**Comment by cristiantm** [comment]
Having the same problem here, just the Ion android client suddently had problems connection to our backend (trust anchor issue). 

Disabling conscrypt works as workaround.

**Comment by koush** [comment]
Yeah. I'm going to leave conscrypt off by default. It's too flaky with GMS updating it under the hood and changing behavior.

**Comment by henhal** [comment]
@koush are you able to elaborate on any possible consequences of disabling conscrypt? I've seen some claims that it's less secure, but no explanation as to why.

**Comment by tjg1** [comment]
I've been having [issues](https://github.com/tjg1/nori/issues/103) with TLS using Ion 2.1.8+ on SDK 16 since March, so hooray for getting rid of conscrypt.

**Comment by rsfez** [comment]
Unfortunately, it seems that disabling the middleware conscrypt breaks SSL behavior on apps running on platforms below Lollipop.

I can't find the issue anymore (I think it was on AndroidAsync's repo?), but it seems that using the Google Play services conscrypt _was_ the fix for this (unwrapping was broken using Android's own methods before Lollipop apparently).

**Comment by TeunVR** [comment]
Looks like the updated GMS has obfuscated some fields that ion uses in SpdyMiddleware.configure.
"sslParameters" is now "b"
"npnProtocols" seems to be gone.
"sslNativePointer" seems to be "d"
"SSL_get_npn_negotiated_protocol" function is not there.

I tried to use the obfuscated names (very evil fix) but stopped at SSL_get_npn_negotiated_protocol.
This is not the right way to fix this. 
Apparently reflection can no longer be used here.

**Comment by TeunVR** [comment]
Ok i managed to get it to work, but it's so dirty that i don't really want to create a pull-request.

```
public EngineHolder(Class engineClass) {
            try {
                peerHost = engineClass.getSuperclass().getDeclaredField("peerHost");
                peerHost.setAccessible(true);

                peerPort = engineClass.getSuperclass().getDeclaredField("peerPort");
                peerPort.setAccessible(true);

                try {
                    sslParameters = engineClass.getDeclaredField("sslParameters");
                }catch(NoSuchFieldException e){
                    sslParameters = engineClass.getDeclaredField("b");
                }

                sslParameters.setAccessible(true);

                useSni = sslParameters.getType().getDeclaredField("useSni");
                useSni.setAccessible(true);
            }
            catch (NoSuchFieldException e) {
            }
        }

```

and in SpdyMiddleware.configure:
```
try {
                peerHost = engine.getClass().getSuperclass().getDeclaredField("peerHost");
                peerPort = engine.getClass().getSuperclass().getDeclaredField("peerPort");
                try {
                    sslParameters = engine.getClass().getDeclaredField("sslParameters");
                }catch(NoSuchFieldException e){
                    //Obfuscated since 11.0.55
                    sslParameters = engine.getClass().getDeclaredField("b");
                }
                //npnProtocols = sslParameters.getType().getDeclaredField("npnProtocols");
                alpnProtocols = sslParameters.getType().getDeclaredField("alpnProtocols");
                useSni = sslParameters.getType().getDeclaredField("useSni");
                try {
                    sslNativePointer = engine.getClass().getDeclaredField("sslNativePointer");
                }catch(NoSuchFieldException e){
                    sslNativePointer = engine.getClass().getDeclaredField("d");
                }
                String nativeCryptoName = sslParameters.getType().getPackage().getName() + ".NativeCrypto";
//                nativeGetNpnNegotiatedProtocol = Class.forName(nativeCryptoName, true, sslParameters.getType().getClassLoader())
//                .getDeclaredMethod("SSL_get_npn_negotiated_protocol", long.class);
                nativeGetAlpnNegotiatedProtocol = Class.forName(nativeCryptoName, true, sslParameters.getType().getClassLoader())
                .getDeclaredMethod("SSL_get0_alpn_selected", long.class);

                peerHost.setAccessible(true);
                peerPort.setAccessible(true);
                sslParameters.setAccessible(true);
                //npnProtocols.setAccessible(true);
                alpnProtocols.setAccessible(true);
                useSni.setAccessible(true);
                sslNativePointer.setAccessible(true);
//                nativeGetNpnNegotiatedProtocol.setAccessible(true);
                nativeGetAlpnNegotiatedProtocol.setAccessible(true);
            }
```

**Comment by henhal** [comment]
@TeunVR appreciate your efforts but I guess this is at risk of breaking on every new build of GPS since obfuscation isn't necessarily constant and deterministic? 
My main focus is still to understand what not using conscrypt actually means in terms of being less secure etc.

**Comment by TeunVR** [comment]
Exactly, this workaround is not very useful.
I hope @koush can find another way to configure the SSLEngine from GMS for SNI, but i currently don't see how.
That would mean we have to disable conscrypt and fall back to the "old" TLS provider from your Android version. I think for my project that is currently the only solution. Thereby dropping Android 4.4, since SNI is not working there.

**Comment by koush** [comment]
Oh, they're obfuscating the internals now? @kruton any reason for this?

**Comment by TeunVR** [comment]
Maybe its this commit?
https://github.com/google/conscrypt/commit/29916ef38dc9cb4e4c6e3fdb87d4e921546d3ef4

**Comment by kruton** [comment]
You all appear to be reaching way too far into the internals of the implementation. I'm not really surprised it's breaking if this is how it's operating.

The Conscrypt in GmsCore v11 is equivalent to google/conscrypt@9e569de9108ef0fa5ce043ee51e3fc467863c95f with cherry-pick of google/conscrypt/pull/189 and google/conscrypt/pull/190

As for obfuscation, it is probably an effort to save space.

**Comment by TeunVR** [comment]
Using the SSLEngine(host,port) constructor seems to work for me (https://github.com/koush/AndroidAsync/pull/538).
I did not change anything to the Spdy-part, that is still using reflection and does not work.

**Comment by koush** [comment]
@kruton as far as I know, that's the only way to get the various ALPN negotiation bits out from the SSLEngine. I can fix up the ProviderInstaller stuff though.

**Comment by koush** [comment]
step 1) remove reflection from ConscryptMiddleware.

https://github.com/koush/ion/commit/7ec16d64c99539e06018a1855d9a7bffd340e084

**Comment by koush** [comment]
step 2) add hook to allow conscrypt to create an SSLEngine

https://github.com/koush/AndroidAsync/commit/71511ef114d9a00e4795be828a49959718f04e51

**Comment by koush** [comment]
step 3) hook conscrypt ssl engine creation, add sni test.

4c8529d

**Comment by koush** [comment]
Fixes are up in ion and Android Async. Let me know if it works for you and I'll publish.

**Comment by TeunVR** [comment]
Ok, i'll check it. Is it a problem that SpdyMiddleware is still using reflection? Probably not?

**Comment by koush** [comment]
It is, but I'm not concerned about fixing that. Not sure it's possible with the Conscrypt obfuscation now. Furthermore, SPDY is deprecated anyways.

**Comment by TeunVR** [comment]
Latest AndroidAsync and ion are working with SNI.
Tested with Play Services 9.4.52 on Android 4.4.4 and 11.0.55 on 5.0.1

**Comment by koush** [comment]
Cool. The downside is that I had to bump minSdkVersion to 14, cause play services won't work on 9 anymore. But it's time to kill gingerbread off anyways.
Guess I'll publish.

**Comment by TeunVR** [comment]
Thanks. 
All our projects are min 19, so no issue for me there 😃

**Comment by henhal** [comment]
You guys rock. Api level 14 works for us as well. 

Thanks!

**Comment by rsfez** [comment]
Hi @koush ,
Thanks for your hard work and for your fix.

I noticed something: I've been trying 2.2.0 on an emulator running Nougat, but it seems that Ion now requires the installed Play Services to be up-to-date, as per this stacktrace, during a failed network call.
`
W/GooglePlayServicesUtil: Google Play services out of date.  Requires 11011000 but found 10298470
E/GooglePlayServicesUtil: GooglePlayServices not available due to error 2
W/IonConscrypt: Conscrypt initialization failed.
                                                                   com.google.android.gms.common.GooglePlayServicesRepairableException: Google Play Services not available
                                                                       at com.google.android.gms.common.zzo.zzah(Unknown Source)
                                                                       at com.google.android.gms.common.zze.zzas(Unknown Source)
                                                                       at com.google.android.gms.security.ProviderInstaller.installIfNeeded(Unknown Source)
                                                                       at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:58)`
And there are other SSLHandshakeExceptions after this.

Does Ion now requires the device to up-to-date this June's Play Services version to run?

**Comment by koush** [comment]
@rsfez 
Conscrypt will fail silently if play services is not available, as seen in the log.

I'm guessing SSL is failing because conscrypt isn't available and SNI isn't supported by the underlying platform. Further logs would be helpful.

**Comment by rsfez** [comment]
@koush
Hi, sorry for the delay. Here are some further logs.

```
06-19 14:28:16.542 24207-24301/XXX W/IonConscrypt: Conscrypt initialization failed.
                                                                     com.google.android.gms.common.GooglePlayServicesRepairableException: Google Play Services not available
                                                                         at com.google.android.gms.common.zzo.zzah(Unknown Source)
                                                                         at com.google.android.gms.common.zze.zzas(Unknown Source)
                                                                         at com.google.android.gms.security.ProviderInstaller.installIfNeeded(Unknown Source)
                                                                         at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:58)
                                                                         at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:75)
                                                                         at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.getSocket(ConscryptMiddleware.java:117)
                                                                         at com.koushikdutta.async.http.AsyncHttpClient.executeAffinity(AsyncHttpClient.java:301)
                                                                         at com.koushikdutta.async.http.AsyncHttpClient.access$100(AsyncHttpClient.java:51)
                                                                         at com.koushikdutta.async.http.AsyncHttpClient$1.run(AsyncHttpClient.java:190)
                                                                         at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:740)
                                                                         at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:758)
                                                                         at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
                                                                         at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
                                                                         at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)


06-19 14:28:16.614 24207-24301/XXX W/System.err: javax.net.ssl.SSLHandshakeException: Handshake failed
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:441)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1270)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
06-19 14:28:16.614 24207-24301/XXX W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x7551ba6c00: Failure in SSL library, usually a protocol error
06-19 14:28:16.614 24207-24301/XXX W/System.err: error:10000460:SSL routines:OPENSSL_internal:reason(1120) (external/boringssl/src/ssl/s3_pkt.c:641 0x7571b3c2e0:0x00000001)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:426)
06-19 14:28:16.614 24207-24301/XXX W/System.err: 	... 8 more
```

This was done using a Galaxy S6, but I get the same with an emulator running Nougat and with outdated Play Services (as per my previous post).

**Comment by koush** [comment]
@rsfez do you have an url i can test?

**Comment by rsfez** [comment]
@koush
I took the liberty to send you the url via email, I hope you won't mind :(

The app is running on Heroku.

**Comment by koush** [comment]
@rsfez i think i fixed the issue. if you have androidasync and ion checked out, let me know if it worked for you as well.
https://github.com/koush/ion/issues/832

**Comment by rsfez** [comment]
Thank you very much!
