### ISSUE TITLE
Ion depends on Google Play Services now

### ISSUE THREAD

**Issue by daniele-athome** [koush/ion#831]
I have a dual-build app that goes to Play Store and F-Droid. The latter doesn't accept dependency to Google Play Services. Since I need SNI support, I've updated Ion to 2.2.0, however I'm now stuck because Ion 2.2.0 depends on Google Play Services.
Is there some way to not depend on it? I see the only middleware is now ConscryptMiddleware, no way to change it? Maybe a custom implementation.

**Comment by koush** [comment]
It is not a requirement, it uses it if available, otherwise it fails silently and uses the platform ssl stack.
See the "provided" keyword in the build.gradle.

**Comment by koush** [comment]
https://github.com/koush/ion/blob/master/ion/build.gradle#L23

**Comment by daniele-athome** [comment]
Sorry, didn't see that. Thank you!

**Comment by daniele-athome** [comment]
For people passing by... If you have Proguard complaining:
> Warning:com.koushikdutta.ion.conscrypt.ConscryptMiddleware: can't find referenced class com.google.android.gms.security.ProviderInstaller

Adding a -dontwarn to ConscryptMiddleware will make it go away. An exception will be printed but it's fine as @koush said.

```
W / IonConscrypt ( 1992): Conscrypt initialization failed.
W / IonConscrypt ( 1992): java.lang.NoClassDefFoundError: com.google.android.gms.security.ProviderInstaller
W / IonConscrypt ( 1992):       at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:58)
W / IonConscrypt ( 1992):       at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:75)
W / IonConscrypt ( 1992):       at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.getSocket(ConscryptMiddleware.java:117)
W / IonConscrypt ( 1992):       at com.koushikdutta.async.http.AsyncHttpClient.executeAffinity(AsyncHttpClient.java:301)
W / IonConscrypt ( 1992):       at com.koushikdutta.async.http.AsyncHttpClient.access$100(AsyncHttpClient.java:51)
W / IonConscrypt ( 1992):       at com.koushikdutta.async.http.AsyncHttpClient$1.run(AsyncHttpClient.java:190)
W / IonConscrypt ( 1992):       at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:740)
W / IonConscrypt ( 1992):       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:758)
W / IonConscrypt ( 1992):       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
W / IonConscrypt ( 1992):       at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
W / IonConscrypt ( 1992):       at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
```
