### ISSUE TITLE
Any special way to nest calls inside one another?

### ISSUE THREAD

**Issue by TristanWiley** [koush/ion#838]
Is there any special way to nest network calls inside one another? Say, calling JSON to get an image URL and then loading that URL? Or should you just make a separate call inside the callback?

**Comment by koush** [comment]
You can chain with Future.then and TransformFuture.
But since it's just one level deep, just nest it in the callback.


https://github.com/koush/AndroidAsync/blob/master/AndroidAsync/src/com/koushikdutta/async/future/TransformFuture.java
