### ISSUE TITLE
javax.net.ssl.SSLException 4.4

### ISSUE THREAD

**Issue by HamedTaherpour** [koush/ion#938]
Hi

`javax.net.ssl.SSLException: Error occured in delegated task:javax.net.ssl.SSLException: Not trusted server certificate`

android 4.4

**Comment by zhaoweih** [comment]
I have the same issues

**Comment by zhaoweih** [comment]
Caused by: java.security.cert.CertificateExpiredException: Certificate expired at Sun Oct 18 20:00:00 GMT+08:00 2020 (compared to Sun Oct 18 20:32:20 GMT+08:00 2020)

But my ssl certificate is not expired

**Comment by zhaowhao** [comment]
after update to version 3.0.9 will solve this problems @HamedTaherpour 

```
def ion_version = "3.0.9"
    implementation "com.koushikdutta.ion:ion:$ion_version"
```

**Comment by HamedTaherpour** [comment]
> 
> 
> after update to version 3.0.9 will solve this problems @HamedTaherpour
> 
> ```
> def ion_version = "3.0.9"
>     implementation "com.koushikdutta.ion:ion:$ion_version"
> ```

I updated to version 3.0.9 but the problem was not resolved.


Thanks

**Comment by Pushpendracolourmoon** [comment]
I am having the same issue. I think iON Support team is no more supporting for this library. Need to think some alternate.
